--Eliminar campo RWE_USUARIO_ENTIDAD OAMR
ALTER TABLE RWE_USUARIO_ENTIDAD drop column OAMR;

--Nuevos campos RWE_USUARIO_ENTIDAD
ALTER TABLE RWE_USUARIO_ENTIDAD add CATEGORIA int8;
ALTER TABLE RWE_USUARIO_ENTIDAD add FUNCION int8;
ALTER TABLE RWE_USUARIO_ENTIDAD add TELEFONO varchar(255);
ALTER TABLE RWE_USUARIO_ENTIDAD add CAI int8;
ALTER TABLE RWE_USUARIO_ENTIDAD add NOMBRETRABAJO varchar(255);
ALTER TABLE RWE_USUARIO_ENTIDAD add CODIGOTRABAJO varchar(255);
ALTER TABLE RWE_USUARIO_ENTIDAD add OBSERVACIONES varchar(255);
ALTER TABLE RWE_USUARIO_ENTIDAD add clave bool DEFAULT false not null;
ALTER TABLE RWE_USUARIO_ENTIDAD add bitcita bool DEFAULT false not null;
ALTER TABLE RWE_USUARIO_ENTIDAD add asistencia bool DEFAULT false not null;
ALTER TABLE RWE_USUARIO_ENTIDAD add apodera bool DEFAULT false not null;
ALTER TABLE RWE_USUARIO_ENTIDAD add notificacion bool DEFAULT false not null;
ALTER TABLE RWE_USUARIO_ENTIDAD ADD FECHAALTA timestamp;

--Nueva tabla RWE_CATISLA
CREATE TABLE RWE_CATISLA (
                 ID int8 not null,
                 CODIGOISLA int8 not null,
                 DESCRIPCIONISLA varchar(50) not null,
                 PROVINCIA int8
);
ALTER TABLE RWE_CATISLA add constraint RWE_CATISLA_pk primary key (ID);
ALTER TABLE RWE_CATISLA add constraint RWE_CATISLA_CATPROVIN_FK foreign key (PROVINCIA) references RWE_CATPROVINCIA;
CREATE INDEX RWE_CATISL_CATPRO_FK_I on RWE_CATISLA (PROVINCIA);

--Nuevos campos RWE_OFICINA
ALTER TABLE RWE_OFICINA add OAMR bool DEFAULT false not null;
ALTER TABLE RWE_OFICINA add ISLA int8;
ALTER TABLE RWE_OFICINA add constraint RWE_OFICINA_ISLA_FK foreign key (ISLA) references RWE_CATISLA;
CREATE INDEX RWE_OFICIN_ISLA_FK_I on RWE_OFICINA (ISLA);

--Nuevo campo RWE_ORGANISMO
ALTER TABLE RWE_ORGANISMO add ISLA int8;
ALTER TABLE RWE_ORGANISMO add constraint RWE_ORGANISMO_ISLA_FK foreign key (ISLA) references RWE_CATISLA;
CREATE INDEX RWE_ORGANI_ISLA_FK_I on RWE_ORGANISMO (ISLA);

-- Índice RWE_ANEXO
CREATE INDEX RWE_ANEXO_CUSTID_FK_I on RWE_ANEXO (CUSTODIAID);


--Nuevo campo RWE_ENTIDAD
ALTER TABLE RWE_ENTIDAD add REG_SALIDAS_PERSONAS bool DEFAULT true not null;
--Eliminar campo RWE_ENTIDAD Oficio Remisión
ALTER TABLE RWE_ENTIDAD drop column OF
ICIOREMISION;

--Nuevo campo ENTIDAD en RWE_OFICINA
alter table RWE_OFICINA add ENTIDAD int8;
alter table RWE_OFICINA add constraint RWE_OFICINA_ENTIDAD_FK foreign key (ENTIDAD) references RWE_ENTIDAD;


