<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <artifactId>regweb3</artifactId>
        <groupId>es.caib.regweb3</groupId>
        <version>4.0.0</version>
    </parent>

    <artifactId>regweb3-persistence</artifactId>
    <packaging>ejb</packaging>
    <name>RegWeb3 - Persistence</name>
    <description>Mòdul EJB de regweb3</description>

    <dependencies>

        <!-- Especificacions i llibreries proporcionades per JBoss -->
        <dependency>
            <groupId>org.jboss.spec</groupId>
            <artifactId>jboss-javaee-8.0</artifactId>
            <type>pom</type>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.hibernate</groupId>
            <artifactId>hibernate-core</artifactId>
            <scope>provided</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.jboss.logging</groupId>
                    <artifactId>jboss-logging</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>javax.activation</groupId>
                    <artifactId>javax.activation-api</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <!-- Afegim dependencia perque exclusion de hibernate-core -->
        <dependency>
            <groupId>javax.activation</groupId>
            <artifactId>activation</artifactId>
        </dependency>

        <dependency>
            <groupId>org.jboss.ejb3</groupId>
            <artifactId>jboss-ejb3-ext-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>commons-lang</groupId>
            <artifactId>commons-lang</artifactId>
            <scope>provided</scope>
        </dependency>
        <!-- Altres mòduls del projecte -->
        <dependency>
            <groupId>es.caib.regweb3</groupId>
            <artifactId>regweb3-model</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>es.caib.regweb3</groupId>
            <artifactId>regweb3-utils</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>es.caib.regweb3</groupId>
            <artifactId>plugin-distribucion-api</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>es.caib.regweb3</groupId>
            <artifactId>plugin-distribucion-email</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>es.caib.regweb3</groupId>
            <artifactId>plugin-distribucion-mock</artifactId>
        </dependency>

        <dependency>
            <groupId>es.caib.regweb3</groupId>
            <artifactId>plugin-postproceso-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>es.caib.regweb3</groupId>
            <artifactId>plugin-justificante-api</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>es.caib.regweb3</groupId>
            <artifactId>regweb3-sir-api</artifactId>
            <scope>provided</scope>
            <type>ejb</type>
        </dependency>

        <dependency>
            <groupId>es.caib.regweb3</groupId>
            <artifactId>regweb3-sir-core</artifactId>
            <scope>provided</scope>
        </dependency>
        <!-- Plugin DocumentCustody -->
        <dependency>
            <groupId>org.fundaciobit.pluginsib.documentcustody</groupId>
            <artifactId>pluginsib-documentcustody-api</artifactId>
            <scope>provided</scope>
        </dependency>

        <!--  PLUGINS DE USERINFORMATION  -->
        <dependency>
            <groupId>org.fundaciobit.pluginsib.userinformation</groupId>
            <artifactId>pluginsib-userinformation-api</artifactId>
            <version>${pluginsib.userinformation.version}</version>
            <scope>provided</scope>
        </dependency>

        <!-- ======== API DE PLUGIN DE SCANWEB =========== -->
        <dependency>
            <groupId>org.fundaciobit.pluginsib.scanweb</groupId>
            <artifactId>pluginsib-scanweb-api</artifactId>
            <version>${pluginsib.scanweb.version}</version>
            <scope>provided</scope>
        </dependency>

        <!-- ======== Plugin DocumentCustody ArxiuCaib =========== -->
        <dependency>
            <groupId>org.fundaciobit.pluginsib.documentcustody</groupId>
            <artifactId>pluginsib-documentcustody-arxiudigitalcaib</artifactId>
            <version>${pluginsib.documentcustody.version}</version>
            <scope>provided</scope>
        </dependency>

        <!-- ===== PLUGINS DE VALIDACIO/INFORMACIO DE FIRMES ===== -->
        <dependency>
            <groupId>org.fundaciobit.pluginsib.validatesignature</groupId>
            <artifactId>pluginsib-validatesignature-api</artifactId>
            <version>${pluginsib.validatesignature.version}</version>
            <scope>provided</scope>
        </dependency>

        <!-- ======== PLUGINS DE FIRMA EN SERVIDOR =========== -->
        <dependency>
            <groupId>org.fundaciobit.pluginsib.signatureserver</groupId>
            <artifactId>pluginsib-signatureserver-api</artifactId>
            <version>${pluginsib.signatureserver.version}</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.fundaciobit.pluginsib.core.v3</groupId>
            <artifactId>pluginsib-core</artifactId>
            <scope>provided</scope>
        </dependency>

        <!--Genapp-->
        <dependency>
            <groupId>org.fundaciobit.genapp</groupId>
            <artifactId>genapp-core</artifactId>
            <scope>provided</scope>
        </dependency>

        <!--Carpeta-->
        <dependency>
            <groupId>es.caib.carpeta</groupId>
            <artifactId>carpeta-api-interna-client</artifactId>
            <version>${carpeta-api-interna-client.version}</version>
            <!-- Ho podem excloure ja que ho tenim a pluginsib-documentcustody-alfresco, pluginsib-userinformation-keycloak -->
            <exclusions>
                <exclusion>
                    <groupId>com.google.code.findbugs</groupId>
                    <artifactId>jsr305</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.jvnet.staxex</groupId>
                    <artifactId>stax-ex</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <!-- Això és l'exclusion de carpeta-api-interna-client i es perque entra en conflicte amb LIBSIR -->
        <dependency>
            <groupId>org.jvnet.staxex</groupId>
            <artifactId>stax-ex</artifactId>
            <version>1.8.3</version>
        </dependency>


        <!-- Dependències de test -->
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-beans</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-orm</artifactId>
            <scope>provided</scope>
        </dependency>

        <!--LIBSIR-->
       <!-- <dependency>
            <groupId>es.gob.ad.registros.sir</groupId>
            <artifactId>InterService</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>es.gob.ad.registros.sir</groupId>
            <artifactId>interModel.ORACLE</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>es.gob.ad.registros.sir</groupId>
            <artifactId>interModel-api</artifactId>
            <scope>provided</scope>
        </dependency>-->



        <dependency>
            <groupId>es.gob.ad.registros.sir</groupId>
            <artifactId>InterService</artifactId>
            <version>${libsir.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>commons-logging</groupId>
                    <artifactId>commons-logging</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>xerces</groupId>
                    <artifactId>xercesImpl</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.springframework</groupId>
                    <artifactId>spring-web</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>javax.activation</groupId>
                    <artifactId>javax.activation-api</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.sun.activation</groupId>
                    <artifactId>jakarta.activation</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.sun.xml.ws</groupId>
                    <artifactId>release-documentation</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.sun.xml.ws</groupId>
                    <artifactId>samples</artifactId>
                </exclusion>
            </exclusions>
        </dependency>




        <!-- las incluimos porque no estan y les hemos hecho un exclusion en la dependencia de InterService -->
        <dependency>
            <groupId>com.sun.xml.ws</groupId>
            <artifactId>release-documentation</artifactId>
            <version>2.3.3</version>
            <type>pom</type>
        </dependency>
        <dependency>
            <groupId>com.sun.xml.ws</groupId>
            <artifactId>samples</artifactId>
            <version>2.3.3</version>
            <type>pom</type>
        </dependency>

        <!-- https://mvnrepository.com/artifact/com.sun.org.apache.xml.internal/resolver -->
        <dependency>
            <groupId>com.sun.org.apache.xml.internal</groupId>
            <artifactId>resolver</artifactId>
            <version>20050927</version>
        </dependency>


        <dependency>
            <groupId>es.gob.ad.registros.sir</groupId>
            <artifactId>gestionEni</artifactId>
            <version>${libsir.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework</groupId>
                    <artifactId>spring-web</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>es.gob.ad.registros.sir</groupId>
            <artifactId>sirCommons</artifactId>
            <version>3.1.3</version>
        </dependency>

        <dependency>
            <groupId>es.gob.ad.registros.sir</groupId>
            <artifactId>interModel-api</artifactId>
            <version>3.1.3</version>
        </dependency>

        <dependency>
            <groupId>es.gob.ad.registros.sir</groupId>
            <artifactId>interModel.ORACLE</artifactId>
            <version>3.1.2</version>
            <exclusions>
                <exclusion>
                    <groupId>antlr</groupId>
                    <artifactId>antlr</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>commons-logging</groupId>
                    <artifactId>commons-logging</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.springframework</groupId>
                    <artifactId>spring-web</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>net.java.xades</groupId>
            <artifactId>jxades</artifactId>
            <version>0.1.5</version>
            <scope>compile</scope>
            <exclusions>
                <exclusion>
                    <groupId>junit</groupId>
                    <artifactId>junit</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.fundaciobit.pluginsib.utils</groupId>
            <artifactId>pluginsib-utils-cxf</artifactId>
            <version>${pluginsib.utils.version}</version>
            <scope>provided</scope>
        </dependency>

        <!--INTERDOC-->
        <dependency>
            <groupId>es.caib.interdoc</groupId>
            <artifactId>interdoc-ws-api</artifactId>
            <version>1.0.0</version>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-ejb-plugin</artifactId>
                <configuration>
                    <ejbVersion>3.2</ejbVersion>
                </configuration>
            </plugin>

            <!-- NO BORRAR PORQUE SE UTILIZA PARA COMPILAR EL MODELO DE DATOS Y QUE COJA LOS CAMBIOS CUANDO USAMOS EL SQLGENERATOR-->
          <!--  <plugin>
                <artifactId>maven-jar-plugin</artifactId>
                <executions>
                    <execution>
                        <id>jdbc</id>
                        <goals>
                            <goal>test-jar</goal>
                        </goals>
                        <phase>package</phase>
                        <configuration>
                            <classifier>jdbc</classifier>
                            <forceCreation>true</forceCreation>

                            <excludes>
                                <exclude>**/*.java</exclude>
                                <exclude>**/*.class</exclude>
                                <exclude>**/arquillian.xml</exclude>
                                <exclude>**/arquillian-persistence.xml</exclude>
                            </excludes>
                            <skip>false</skip>
                        </configuration>
                    </execution>

                </executions>
            </plugin>-->
        </plugins>
    </build>

</project>