ALTER TABLE RWE_ORGANISMO
    ADD COLUMN confidencial bool DEFAULT false NOT NULL;

-- Nuevos campos RWE_USUARIO_ENTIDAD
ALTER TABLE RWE_USUARIO_ENTIDAD
    ADD COLUMN CERTIFICADO bigint;

ALTER TABLE RWE_USUARIO_ENTIDAD
    ADD CONSTRAINT RWE_USUENT_CERTIFICADO_FK FOREIGN KEY (CERTIFICADO) REFERENCES RWE_ARCHIVO;

ALTER TABLE RWE_USUARIO_ENTIDAD
    ADD COLUMN FECHA_CERTIFICADO timestamp;

-- Unique Key RWE_PERSONA
ALTER TABLE RWE_PERSONA
    ADD CONSTRAINT RWE_PERSONA_DOC_ENT_UK UNIQUE (DOCUMENTO, ENTIDAD);

-- Cambio de nombre de un campo en RWE_USUARIO_ENTIDAD
ALTER TABLE RWE_USUARIO_ENTIDAD
    RENAME COLUMN ULTIMAOFICINA TO OFICINA_SOLICITADA;

-- Secuencias específicas para los Registros Migrados
CREATE SEQUENCE RWE_REGISTRO_MIGRADO_SEQ START 1 INCREMENT 1;
CREATE SEQUENCE RWE_REGISTRO_LOPD_MIGRADO_SEQ START 1 INCREMENT 1;
CREATE SEQUENCE RWE_MODIFICACION_LOPD_MIGRADO_SEQ START 1 INCREMENT 1;

ALTER TABLE RWE_REGISTRO_MIGRADO ALTER COLUMN PRODESGEO DROP NOT NULL;

-- Nuevo campo RWE_TRAZABILIDAD
ALTER TABLE RWE_TRAZABILIDAD ADD COLUMN OBSERVACIONES varchar(2000);

-- Modificaciones campos RWE_DESCARGA
ALTER TABLE RWE_DESCARGA DROP COLUMN FECHAINICIO;
ALTER TABLE RWE_DESCARGA DROP COLUMN FECHAFIN;

ALTER TABLE RWE_DESCARGA ADD COLUMN ELEMENTOS text;

ALTER TABLE RWE_DESCARGA RENAME COLUMN tipo TO tipo2;

ALTER TABLE RWE_DESCARGA ADD COLUMN tipo integer;

UPDATE RWE_DESCARGA SET tipo = 1 WHERE tipo2 = 'unidad';
UPDATE RWE_DESCARGA SET tipo = 2 WHERE tipo2 = 'oficina';
UPDATE RWE_DESCARGA SET tipo = 3 WHERE tipo2 = 'catalogo';

ALTER TABLE RWE_DESCARGA DROP COLUMN tipo2;

-- Modificaciones campos RWE_REGISTRO_MIGRADO
ALTER TABLE RWE_REGISTRO_MIGRADO ALTER COLUMN FECHADOC DROP NOT NULL;
ALTER TABLE RWE_REGISTRO_MIGRADO ALTER COLUMN DESCDOC DROP NOT NULL;
ALTER TABLE RWE_REGISTRO_MIGRADO ALTER COLUMN DESIDIDOC DROP NOT NULL;

-- Modificacion de campo RWE_INTERESADO
ALTER TABLE RWE_INTERESADO ALTER COLUMN DOCUMENTO TYPE varchar(256);

-- Modificación de campo DOCUMENTO en RWE_PERSONA
ALTER TABLE RWE_PERSONA ALTER COLUMN DOCUMENTO TYPE varchar(256);