ALTER TABLE RWE_REGISTRO_SIR ADD MOTIVO_RECHAZO VARCHAR(255);
ALTER TABLE RWE_OFICIO_REMISION ADD MOTIVO_RECHAZO VARCHAR(255);

CREATE TABLE RWE_REMESA
(
    ID							INT8 NOT NULL,
    CONCEPTO					VARCHAR(255) NOT NULL,
    DESCRIPCION					VARCHAR(1000),
    IDENTIFICADOR				VARCHAR(20) NOT NULL,
    CODIGO_ORIGEN 				INT2 NOT NULL,
    TIPO						INT2 NOT NULL,
    ORGANO_EMISOR_CODIGO    	VARCHAR(9) NOT NULL,
    ORGANO_EMISOR_NIF 			VARCHAR(64),
    ORGANO_EMISOR_NOMBRE 		VARCHAR(255) NOT NULL,
    FECHA_PUESTA_DISPOSICION 	DATE NOT NULL,
    TITULAR_NIF					VARCHAR(9),
    TITULAR_NOMBRE				VARCHAR(255),
    ENTIDAD_CODIGO				VARCHAR(9),
    ENTIDAD_NOMBRE				VARCHAR(255),
    ESTADO						VARCHAR(30) NOT NULL,
    ESTADO_NOTIFICA				VARCHAR(30) NOT NULL,
    CODIGO_PROCEDIMIENTO		VARCHAR(9),
    REINTENTOS_LECTURA			INT2 DEFAULT 3 NOT NULL,
    REGISTRO       				INT8,
    USUARIO                		INT8,
    ENTIDAD        				INT8 NOT NULL,
    PRIMARY KEY (ID)
);

CREATE INDEX RWE_REMESA_CONCE_I ON RWE_REMESA(CONCEPTO);

CREATE INDEX RWE_REMESA_IDENT_I ON RWE_REMESA(IDENTIFICADOR);

CREATE INDEX RWE_REMESA_TIPO_I ON RWE_REMESA(TIPO);

CREATE INDEX RWE_REMESA_EMISOR_CODI_I ON RWE_REMESA(ORGANO_EMISOR_CODIGO);

CREATE INDEX RWE_REMESA_EMISOR_NIF_I ON RWE_REMESA(ORGANO_EMISOR_NIF);

CREATE INDEX RWE_REMESA_EMISOR_NOM_I ON RWE_REMESA(ORGANO_EMISOR_NOMBRE);

CREATE INDEX RWE_REMESA_TITULAR_NIF_I ON RWE_REMESA(TITULAR_NIF);

CREATE INDEX RWE_REMESA_TITULAR_NOM_I ON RWE_REMESA(TITULAR_NOMBRE);

CREATE INDEX RWE_REMESA_FECHA_PUEST_I ON RWE_REMESA(FECHA_PUESTA_DISPOSICION);

CREATE INDEX RWE_REMESA_ESTADO_I ON RWE_REMESA(ESTADO);

CREATE INDEX RWE_REMESA_ESTADO_NOTIF_I ON RWE_REMESA(ESTADO_NOTIFICA);

CREATE INDEX RWE_REMESA_USUARIO_FK_I on RWE_REMESA (USUARIO);

CREATE INDEX RWE_REMESA_ENTIDAD_FK_I on RWE_REMESA (ENTIDAD);

ALTER TABLE RWE_REMESA
    ADD CONSTRAINT RWE_REMESA_ENTIDAD_FK
        FOREIGN KEY (ENTIDAD)
            REFERENCES RWE_ENTIDAD;
            
ALTER TABLE RWE_REMESA
    ADD CONSTRAINT RWE_REMESA_USUARIO_ENTIDAD_FK
        FOREIGN KEY (USUARIO)
            REFERENCES RWE_USUARIO_ENTIDAD;

ALTER TABLE RWE_REMESA
    ADD CONSTRAINT RWE_REMESA_REGISTRO_FK
        FOREIGN KEY (REGISTRO)
            REFERENCES RWE_REGISTRO_ENTRADA;
            
CREATE TABLE RWE_REMESA_ACUSE
(
    ID							INT8 NOT NULL,
    NOMBRE						VARCHAR(255),
    MIME_TYPE					VARCHAR(255),
    METADATOS					VARCHAR(1000),
    REFERENCIA					BYTEA,
    CSV_RESGUARDO				VARCHAR(1000),
    REMESA						INT8 NOT NULL,
    PRIMARY KEY (ID)
);

CREATE INDEX RWE_REMESA_ACUSE_METAD_I ON RWE_REMESA_ACUSE(METADATOS);

CREATE INDEX RWE_REMESA_ACUSE_REFER_I ON RWE_REMESA_ACUSE(REFERENCIA);

ALTER TABLE RWE_REMESA_ACUSE
    ADD CONSTRAINT RWE_REMESA_ACUSE_REMESA_FK
        FOREIGN KEY (REMESA)
            REFERENCES RWE_REMESA;
            
CREATE TABLE RWE_REMESA_ANEXO
(
    ID							INT8 NOT NULL,
    ENLACE_DOCUMENTO						VARCHAR(255),
    REFERENCIA					BYTEA,
    REMESA						INT8 NOT NULL,
    PRIMARY KEY (ID)
);

CREATE INDEX RWE_REMESA_ANEXO_ENLAC_I ON RWE_REMESA_ANEXO(ENLACE_DOCUMENTO);

CREATE INDEX RWE_REMESA_ANEXO_REFER_I ON RWE_REMESA_ANEXO(REFERENCIA);

ALTER TABLE RWE_REMESA_ANEXO
    ADD CONSTRAINT RWE_REMESA_ANEXO_REMESA_FK
        FOREIGN KEY (REMESA)
            REFERENCES RWE_REMESA;

ALTER TABLE RWE_REGISTRO_ENTRADA ADD COLUMN ANEXOS_PENDIENTES BOOL DEFAULT FALSE;

INSERT INTO RWE_PROPIEDADGLOBAL (ID, CLAVE, DESCRIPCION, ENTIDAD, TIPO, VALOR) VALUES (nextval('RWE_ALL_SEQ'),'es.caib.regweb3.fecha.inicio.busqueda.notificaciones.path','Ubicación del fichero con la próxima fecha de consulta de notificaciones pendientes',null,1,'/opt/files');

INSERT INTO RWE_PROPIEDADGLOBAL (ID, CLAVE, DESCRIPCION, ENTIDAD, TIPO, VALOR) VALUES (nextval('RWE_ALL_SEQ'),'es.caib.regweb3.cron.localizacion.notificaciones.dehu.periodo','Tiempo inicial consulta notificaciones DEHú',null,1,600000); --10min

INSERT INTO RWE_PROPIEDADGLOBAL (ID, CLAVE, DESCRIPCION, ENTIDAD, TIPO, VALOR) VALUES (nextval('RWE_ALL_SEQ'),'es.caib.regweb3.cron.localizacion.notificaciones.dehu.retardo','Retardo entre cada consulta (localiza) notificaciones DEHú',null,1,600000); --10min

INSERT INTO RWE_PROPIEDADGLOBAL (ID, CLAVE, DESCRIPCION, ENTIDAD, TIPO, VALOR) VALUES (nextval('RWE_ALL_SEQ'),'es.caib.regweb3.enviar.mail.resultado.lema','Enviar correo con el resultado de consulta notificaciones DEHú',null,1,true);

INSERT INTO RWE_PROPIEDADGLOBAL (ID, CLAVE, DESCRIPCION, ENTIDAD, TIPO, VALOR) VALUES (nextval('RWE_ALL_SEQ'),'es.caib.regweb3.notificaciones.pendientes.aviso.hora','Hora enviament correu informació remeses pendents',null,1,'08:40');

INSERT INTO RWE_PLUGIN (ID, ACTIVO, CLASE, DESCRIPCION, ENTIDAD, NOMBRE, PROPIEDADES_ADMIN, PROPIEDADES_ENTIDAD, TIPO) VALUES (
	nextval('RWE_ALL_SEQ'),
	true,
	'org.plugin.lema.apb.LemaApbPlugin',
	'Integració DEHú',
	16,
	'Integració DEHú',
	NULL,
	'es.caib.regweb3.plugins.lema.apb.proxy.endpoint=http://localhost:8081/lema-proxy/api
	es.caib.regweb3.plugins.lema.apb.service.localiza.endpoint=https://se-gd-dehuws.redsara.es/ws/v2/lema
	es.caib.regweb3.plugins.lema.apb.keystore.file=/opt/files/lema_auth.jks
	es.caib.regweb3.plugins.lema.apb.keystore.type=JKS
	es.caib.regweb3.plugins.lema.apb.keystore.alias=auth
	es.caib.regweb3.plugins.lema.apb.keystore.pass=12345
	es.caib.regweb3.plugins.lema.apb.titular.nif=*******
	es.caib.regweb3.plugins.lema.apb.receptor.nif=*******
	es.caib.regweb3.plugins.lema.apb.usuarios.aviso=jamalj@limit.es,jamalj@limit.es',
	12);
