--Nuevos campos RWE_ANEXO
ALTER TABLE RWE_ANEXO add CUSTODIADO number(1,0);

--Nuevos campos RWE_COLA
ALTER TABLE RWE_COLA ADD TIPOREGISTRO number(19,0);
ALTER TABLE RWE_COLA ADD FECHAPROCESADO timestamp;



