ALTER TABLE RWE_REGISTRO_ENTRADA ALTER COLUMN FECHA DROP NOT NULL;
ALTER TABLE RWE_REGISTRO_ENTRADA ALTER COLUMN NUMREGFORMAT DROP NOT NULL;

--CAMBIO TIPO COLUMNA NUMREGISTRO
ALTER TABLE RWE_REGISTRO_ENTRADA ADD NUMREGISTRO_TMP int4;
UPDATE RWE_REGISTRO_ENTRADA SET NUMREGISTRO_TMP = NUMREGISTRO;
ALTER TABLE RWE_REGISTRO_ENTRADA ALTER COLUMN NUMREGISTRO DROP NOT NULL;
UPDATE RWE_REGISTRO_ENTRADA SET NUMREGISTRO = NULL;
ALTER TABLE RWE_REGISTRO_ENTRADA ALTER COLUMN NUMREGISTRO TYPE varchar(255);
UPDATE RWE_REGISTRO_ENTRADA SET NUMREGISTRO = NUMREGISTRO_TMP;
ALTER TABLE RWE_REGISTRO_ENTRADA DROP COLUMN NUMREGISTRO_TMP;

ALTER TABLE RWE_REGISTRO_SALIDA ALTER COLUMN FECHA DROP NOT NULL;
ALTER TABLE RWE_REGISTRO_SALIDA ALTER COLUMN NUMREGFORMAT DROP NOT NULL;

--CAMBIO TIPO COLUMNA NUMREGISTRO
ALTER TABLE RWE_REGISTRO_SALIDA ADD NUMREGISTRO_TMP int4;
UPDATE RWE_REGISTRO_SALIDA SET NUMREGISTRO_TMP = NUMREGISTRO;
ALTER TABLE RWE_REGISTRO_SALIDA ALTER COLUMN NUMREGISTRO DROP NOT NULL;
UPDATE RWE_REGISTRO_SALIDA SET NUMREGISTRO = NULL;
ALTER TABLE RWE_REGISTRO_SALIDA ALTER COLUMN NUMREGISTRO TYPE varchar(255);
UPDATE RWE_REGISTRO_SALIDA SET NUMREGISTRO = NUMREGISTRO_TMP;
ALTER TABLE RWE_REGISTRO_SALIDA DROP COLUMN NUMREGISTRO_TMP;

--CAMBIO TIPO COLUMNA NUMREG_ORIGEN
ALTER TABLE RWE_REGISTRO_DETALLE ADD NUMREG_ORIGEN_TMP varchar(20);
UPDATE RWE_REGISTRO_DETALLE SET NUMREG_ORIGEN_TMP = NUMREG_ORIGEN;
UPDATE RWE_REGISTRO_DETALLE SET NUMREG_ORIGEN = NULL;
ALTER TABLE RWE_REGISTRO_DETALLE ALTER COLUMN NUMREG_ORIGEN TYPE varchar(255);
UPDATE RWE_REGISTRO_DETALLE SET NUMREG_ORIGEN = NUMREG_ORIGEN_TMP;
ALTER TABLE RWE_REGISTRO_DETALLE DROP COLUMN NUMREG_ORIGEN_TMP;

ALTER TABLE RWE_LOPD ADD NUMREGISTRO_TMP int4;
UPDATE RWE_LOPD SET NUMREGISTRO_TMP = NUMREGISTRO;
ALTER TABLE RWE_LOPD ALTER COLUMN NUMREGISTRO DROP NOT NULL;
UPDATE RWE_LOPD SET NUMREGISTRO = NULL;
ALTER TABLE RWE_LOPD ALTER COLUMN NUMREGISTRO TYPE varchar(255);
UPDATE RWE_LOPD SET NUMREGISTRO = NUMREGISTRO_TMP;
ALTER TABLE RWE_LOPD DROP COLUMN NUMREGISTRO_TMP;


ALTER TABLE RWE_LOPD ALTER COLUMN ANYOREGISTRO DROP NOT NULL;

ALTER TABLE RWE_REGISTRO_SIR ADD DOCUMENTO_USUARIO varchar(17);
ALTER TABLE RWE_REGISTRO_SIR ALTER COLUMN ID_INTERCAMBIO DROP NOT NULL;

-- Nuevo Contador para genera el Identificador Intercambio SIR, realizar tantos inserts como Entidades haya creadas, indicado su id
INSERT into RWE_CONTADOR (id, numero) VALUES (nextval('RWE_ALL_SEQ'),0);
UPDATE RWE_ENTIDAD set CONTADOR_SIR=CURRVAL('RWE_ALL_SEQ') where id=?;

-- Identificar documento firma dettached (no disponible identificador intercanvi fins que s'envia a GEISER)
ALTER TABLE RWE_ANEXO_SIR ADD COLUMN DOCUMENTO int8 NULL;
ALTER TABLE RWE_ANEXO_SIR
		ADD CONSTRAINT RWE_DOCUMENTOSIR_ANEXO_FK
		FOREIGN KEY (DOCUMENTO)
		REFERENCES RWE_ANEXO_SIR;