
package org.plugin.lema.api.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DEHuWsService", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/lema/1.0/", wsdlLocation = "file:/home/jamal/projects/registre-apb/registre-geiser/plugins/plugin-lema/plugin-lema-api/wsdl/lema.wsdl")
public class DEHuWsService
    extends Service
{

    private final static URL DEHUWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException DEHUWSSERVICE_EXCEPTION;
    private final static QName DEHUWSSERVICE_QNAME = new QName("https://administracionelectronica.gob.es/notifica/ws/lema/1.0/", "DEHuWsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/jamal/projects/registre-apb/registre-geiser/plugins/plugin-lema/plugin-lema-api/wsdl/lema.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DEHUWSSERVICE_WSDL_LOCATION = url;
        DEHUWSSERVICE_EXCEPTION = e;
    }

    public DEHuWsService() {
        super(__getWsdlLocation(), DEHUWSSERVICE_QNAME);
    }

    public DEHuWsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DEHUWSSERVICE_QNAME, features);
    }

    public DEHuWsService(URL wsdlLocation) {
        super(wsdlLocation, DEHUWSSERVICE_QNAME);
    }

    public DEHuWsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DEHUWSSERVICE_QNAME, features);
    }

    public DEHuWsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DEHuWsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DEHuWsPortType
     */
    @WebEndpoint(name = "DEHuWsPort")
    public DEHuWsPortType getDEHuWsPort() {
        return super.getPort(new QName("https://administracionelectronica.gob.es/notifica/ws/lema/1.0/", "DEHuWsPort"), DEHuWsPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DEHuWsPortType
     */
    @WebEndpoint(name = "DEHuWsPort")
    public DEHuWsPortType getDEHuWsPort(WebServiceFeature... features) {
        return super.getPort(new QName("https://administracionelectronica.gob.es/notifica/ws/lema/1.0/", "DEHuWsPort"), DEHuWsPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DEHUWSSERVICE_EXCEPTION!= null) {
            throw DEHUWSSERVICE_EXCEPTION;
        }
        return DEHUWSSERVICE_WSDL_LOCATION;
    }

}
