
package org.plugin.lema.api.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DEHuWsPortType", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/lema/1.0/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DEHuWsPortType {


    /**
     * 
     * @param localiza
     * @return
     *     returns org.plugin.lema.api.ws.RespuestaLocaliza
     */
    @WebMethod(operationName = "Localiza", action = "https://administracionelectronica.gob.es/notifica/ws/lema/Localiza")
    @WebResult(name = "RespuestaLocaliza", targetNamespace = "http://administracion.gob.es/punto-unico-notificaciones/respuestaLocaliza", partName = "RespuestaLocaliza")
    public RespuestaLocaliza localiza(
        @WebParam(name = "Localiza", targetNamespace = "http://administracion.gob.es/punto-unico-notificaciones/localiza", partName = "Localiza")
        Localiza localiza);

    /**
     * 
     * @param peticionAcceso
     * @return
     *     returns org.plugin.lema.api.ws.RespuestaPeticionAcceso
     */
    @WebMethod(operationName = "PeticionAcceso", action = "https://administracionelectronica.gob.es/notifica/ws/lema/PeticionAcceso")
    @WebResult(name = "RespuestaPeticionAcceso", targetNamespace = "http://administracion.gob.es/punto-unico-notificaciones/respuestaPeticionAcceso", partName = "RespuestaPeticionAcceso")
    public RespuestaPeticionAcceso peticionAcceso(
        @WebParam(name = "PeticionAcceso", targetNamespace = "http://administracion.gob.es/punto-unico-notificaciones/peticionAcceso", partName = "PeticionAcceso")
        PeticionAcceso peticionAcceso);

    /**
     * 
     * @param consultaAnexos
     * @return
     *     returns org.plugin.lema.api.ws.RespuestaConsultaAnexos
     */
    @WebMethod(operationName = "ConsultaAnexos", action = "https://administracionelectronica.gob.es/notifica/ws/lema/ConsultaAnexos")
    @WebResult(name = "RespuestaConsultaAnexos", targetNamespace = "http://administracion.gob.es/punto-unico-notificaciones/respuestaConsultaAnexos", partName = "RespuestaConsultaAnexos")
    public RespuestaConsultaAnexos consultaAnexos(
        @WebParam(name = "ConsultaAnexos", targetNamespace = "http://administracion.gob.es/punto-unico-notificaciones/consultaAnexos", partName = "ConsultaAnexos")
        ConsultaAnexos consultaAnexos);

    /**
     * 
     * @param consultaAcusePdf
     * @return
     *     returns org.plugin.lema.api.ws.RespuestaConsultaAcusePdf
     */
    @WebMethod(operationName = "ConsultaAcusePdf", action = "https://administracionelectronica.gob.es/notifica/ws/lema/ConsultaAcusePdf")
    @WebResult(name = "RespuestaConsultaAcusePdf", targetNamespace = "http://administracion.gob.es/punto-unico-notificaciones/respuestaConsultaAcusePdf", partName = "RespuestaConsultaAcusePdf")
    public RespuestaConsultaAcusePdf consultaAcusePdf(
        @WebParam(name = "ConsultaAcusePdf", targetNamespace = "http://administracion.gob.es/punto-unico-notificaciones/consultaAcusePdf", partName = "ConsultaAcusePdf")
        ConsultaAcusePdf consultaAcusePdf);

}
