ALTER TABLE RWE_REGISTRO_ENTRADA MODIFY FECHA NULL;
ALTER TABLE RWE_REGISTRO_ENTRADA MODIFY NUMREGISTRO NULL;
ALTER TABLE RWE_REGISTRO_ENTRADA MODIFY NUMREGFORMAT NULL;

--CAMBIO TIPO COLUMNA NUMREGISTRO
ALTER TABLE RWE_REGISTRO_ENTRADA ADD NUMREGISTRO_TMP NUMBER(10);
UPDATE RWE_REGISTRO_ENTRADA SET NUMREGISTRO_TMP = NUMREGISTRO;
ALTER TABLE RWE_REGISTRO_ENTRADA MODIFY NUMREGISTRO NULL;
UPDATE RWE_REGISTRO_ENTRADA SET NUMREGISTRO = NULL;
ALTER TABLE RWE_REGISTRO_ENTRADA MODIFY NUMREGISTRO VARCHAR2(255 CHAR);
UPDATE RWE_REGISTRO_ENTRADA SET NUMREGISTRO = NUMREGISTRO_TMP;
ALTER TABLE RWE_REGISTRO_ENTRADA DROP COLUMN NUMREGISTRO_TMP;


ALTER TABLE RWE_LOPD ADD NUMREGISTRO_TMP NUMBER(10);
UPDATE RWE_LOPD SET NUMREGISTRO_TMP = NUMREGISTRO;
ALTER TABLE RWE_LOPD MODIFY NUMREGISTRO NULL;
UPDATE RWE_LOPD SET NUMREGISTRO = NULL;
ALTER TABLE RWE_LOPD MODIFY NUMREGISTRO VARCHAR2(255 CHAR);
UPDATE RWE_LOPD SET NUMREGISTRO = NUMREGISTRO_TMP;
ALTER TABLE RWE_LOPD DROP COLUMN NUMREGISTRO_TMP;

