package es.caib.regweb3.ws.api.v3;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 2.6.4
 * 2019-04-02T13:20:26.598+02:00
 * Generated source version: 2.6.4
 * 
 */
@WebServiceClient(name = "AsientoRegistralWsService", 
                  wsdlLocation = "http://localhost:8080/regweb3/ws/v3/AsientoRegistral?wsdl",
                  targetNamespace = "http://impl.v3.ws.regweb3.caib.es/") 
public class AsientoRegistralWsService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.v3.ws.regweb3.caib.es/", "AsientoRegistralWsService");
    public final static QName AsientoRegistralWs = new QName("http://impl.v3.ws.regweb3.caib.es/", "AsientoRegistralWs");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/regweb3/ws/v3/AsientoRegistral?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AsientoRegistralWsService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/regweb3/ws/v3/AsientoRegistral?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AsientoRegistralWsService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AsientoRegistralWsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AsientoRegistralWsService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AsientoRegistralWsService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AsientoRegistralWsService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AsientoRegistralWsService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns AsientoRegistralWs
     */
    @WebEndpoint(name = "AsientoRegistralWs")
    public AsientoRegistralWs getAsientoRegistralWs() {
        return super.getPort(AsientoRegistralWs, AsientoRegistralWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AsientoRegistralWs
     */
    @WebEndpoint(name = "AsientoRegistralWs")
    public AsientoRegistralWs getAsientoRegistralWs(WebServiceFeature... features) {
        return super.getPort(AsientoRegistralWs, AsientoRegistralWs.class, features);
    }

}
