package es.caib.regweb3.ws.api.v3;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 2.6.4
 * 2016-04-20T09:43:18.742+02:00
 * Generated source version: 2.6.4
 * 
 */
@WebServiceClient(name = "RegWebInfoWsService", 
                  wsdlLocation = "http://localhost:8080/regweb3/ws/v3/RegWebInfo?wsdl",
                  targetNamespace = "http://impl.v3.ws.regweb3.caib.es/") 
public class RegWebInfoWsService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.v3.ws.regweb3.caib.es/", "RegWebInfoWsService");
    public final static QName RegWebInfoWs = new QName("http://impl.v3.ws.regweb3.caib.es/", "RegWebInfoWs");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/regweb3/ws/v3/RegWebInfo?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RegWebInfoWsService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/regweb3/ws/v3/RegWebInfo?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RegWebInfoWsService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RegWebInfoWsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RegWebInfoWsService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns RegWebInfoWs
     */
    @WebEndpoint(name = "RegWebInfoWs")
    public RegWebInfoWs getRegWebInfoWs() {
        return super.getPort(RegWebInfoWs, RegWebInfoWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RegWebInfoWs
     */
    @WebEndpoint(name = "RegWebInfoWs")
    public RegWebInfoWs getRegWebInfoWs(WebServiceFeature... features) {
        return super.getPort(RegWebInfoWs, RegWebInfoWs.class, features);
    }

}
