package es.caib.regweb3.ws.api.v3;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.4
 * 2019-11-05T10:10:52.946+01:00
 * Generated source version: 2.6.4
 * 
 */
@WebService(targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", name = "RegWebAsientoRegistralWs")
@XmlSeeAlso({ObjectFactory.class})
public interface RegWebAsientoRegistralWs {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "obtenerOficioExterno", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.ObtenerOficioExterno")
    @WebMethod
    @ResponseWrapper(localName = "obtenerOficioExternoResponse", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.ObtenerOficioExternoResponse")
    public es.caib.regweb3.ws.api.v3.OficioWs obtenerOficioExterno(
        @WebParam(name = "entidad", targetNamespace = "")
        java.lang.String entidad,
        @WebParam(name = "numeroRegistroFormateado", targetNamespace = "")
        java.lang.String numeroRegistroFormateado
    ) throws WsValidationException, WsI18NException;

    @RequestWrapper(localName = "distribuirAsientoRegistral", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.DistribuirAsientoRegistral")
    @WebMethod
    @ResponseWrapper(localName = "distribuirAsientoRegistralResponse", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.DistribuirAsientoRegistralResponse")
    public void distribuirAsientoRegistral(
        @WebParam(name = "entidad", targetNamespace = "")
        java.lang.String entidad,
        @WebParam(name = "numeroRegistroFormateado", targetNamespace = "")
        java.lang.String numeroRegistroFormateado
    ) throws WsValidationException, WsI18NException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "obtenerReferenciaJustificante", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.ObtenerReferenciaJustificante")
    @WebMethod
    @ResponseWrapper(localName = "obtenerReferenciaJustificanteResponse", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.ObtenerReferenciaJustificanteResponse")
    public es.caib.regweb3.ws.api.v3.JustificanteReferenciaWs obtenerReferenciaJustificante(
        @WebParam(name = "entidad", targetNamespace = "")
        java.lang.String entidad,
        @WebParam(name = "numeroRegistroFormateado", targetNamespace = "")
        java.lang.String numeroRegistroFormateado
    ) throws WsValidationException, WsI18NException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "obtenerAsientoRegistral", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.ObtenerAsientoRegistral")
    @WebMethod
    @ResponseWrapper(localName = "obtenerAsientoRegistralResponse", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.ObtenerAsientoRegistralResponse")
    public es.caib.regweb3.ws.api.v3.AsientoRegistralWs obtenerAsientoRegistral(
        @WebParam(name = "entidad", targetNamespace = "")
        java.lang.String entidad,
        @WebParam(name = "numeroRegistroFormateado", targetNamespace = "")
        java.lang.String numeroRegistroFormateado,
        @WebParam(name = "tipoRegistro", targetNamespace = "")
        java.lang.Long tipoRegistro,
        @WebParam(name = "conAnexos", targetNamespace = "")
        boolean conAnexos
    ) throws WsValidationException, WsI18NException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "obtenerAsientoCiudadano", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.ObtenerAsientoCiudadano")
    @WebMethod
    @ResponseWrapper(localName = "obtenerAsientoCiudadanoResponse", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.ObtenerAsientoCiudadanoResponse")
    public es.caib.regweb3.ws.api.v3.AsientoRegistralWs obtenerAsientoCiudadano(
        @WebParam(name = "entidad", targetNamespace = "")
        java.lang.String entidad,
        @WebParam(name = "documento", targetNamespace = "")
        java.lang.String documento,
        @WebParam(name = "numeroRegistroFormateado", targetNamespace = "")
        java.lang.String numeroRegistroFormateado
    ) throws WsValidationException, WsI18NException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "obtenerJustificante", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.ObtenerJustificante")
    @WebMethod
    @ResponseWrapper(localName = "obtenerJustificanteResponse", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.ObtenerJustificanteResponse")
    public es.caib.regweb3.ws.api.v3.JustificanteWs obtenerJustificante(
        @WebParam(name = "entidad", targetNamespace = "")
        java.lang.String entidad,
        @WebParam(name = "numeroRegistroFormateado", targetNamespace = "")
        java.lang.String numeroRegistroFormateado,
        @WebParam(name = "tipoRegistro", targetNamespace = "")
        java.lang.Long tipoRegistro
    ) throws WsValidationException, WsI18NException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "obtenerAsientosCiudadano", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.ObtenerAsientosCiudadano")
    @WebMethod
    @ResponseWrapper(localName = "obtenerAsientosCiudadanoResponse", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.ObtenerAsientosCiudadanoResponse")
    public es.caib.regweb3.ws.api.v3.ResultadoBusquedaWs obtenerAsientosCiudadano(
        @WebParam(name = "entidad", targetNamespace = "")
        java.lang.String entidad,
        @WebParam(name = "documento", targetNamespace = "")
        java.lang.String documento,
        @WebParam(name = "pageNumber", targetNamespace = "")
        java.lang.Integer pageNumber
    ) throws WsValidationException, WsI18NException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "obtenerSesionRegistro", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.ObtenerSesionRegistro")
    @WebMethod
    @ResponseWrapper(localName = "obtenerSesionRegistroResponse", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.ObtenerSesionRegistroResponse")
    public java.lang.Long obtenerSesionRegistro(
        @WebParam(name = "entidad", targetNamespace = "")
        java.lang.String entidad
    ) throws WsI18NException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "crearAsientoRegistral", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.CrearAsientoRegistral")
    @WebMethod
    @ResponseWrapper(localName = "crearAsientoRegistralResponse", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.CrearAsientoRegistralResponse")
    public es.caib.regweb3.ws.api.v3.AsientoRegistralWs crearAsientoRegistral(
        @WebParam(name = "idSesion", targetNamespace = "")
        java.lang.Long idSesion,
        @WebParam(name = "entidad", targetNamespace = "")
        java.lang.String entidad,
        @WebParam(name = "asientoRegistral", targetNamespace = "")
        es.caib.regweb3.ws.api.v3.AsientoRegistralWs asientoRegistral,
        @WebParam(name = "tipoOperacion", targetNamespace = "")
        java.lang.Long tipoOperacion,
        @WebParam(name = "justificante", targetNamespace = "")
        java.lang.Boolean justificante,
        @WebParam(name = "distribuir", targetNamespace = "")
        java.lang.Boolean distribuir
    ) throws WsValidationException, WsI18NException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "verificarAsientoRegistral", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.VerificarAsientoRegistral")
    @WebMethod
    @ResponseWrapper(localName = "verificarAsientoRegistralResponse", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.VerificarAsientoRegistralResponse")
    public es.caib.regweb3.ws.api.v3.AsientoRegistralSesionWs verificarAsientoRegistral(
        @WebParam(name = "entidad", targetNamespace = "")
        java.lang.String entidad,
        @WebParam(name = "idSesion", targetNamespace = "")
        java.lang.Long idSesion
    ) throws WsI18NException;
}
