--Cambio de tipo de datos para campos varchar2 de 4000 caracteres
ALTER TABLE RWE_REGISTRO_DETALLE RENAME COLUMN expone TO expone2;
ALTER TABLE RWE_REGISTRO_DETALLE RENAME COLUMN solicita TO solicita2;

ALTER TABLE RWE_REGISTRO_DETALLE ADD expone text;
ALTER TABLE RWE_REGISTRO_DETALLE ADD solicita text;

UPDATE RWE_REGISTRO_DETALLE SET expone=expone2;
UPDATE RWE_REGISTRO_DETALLE SET solicita=solicita2;
ALTER TABLE RWE_REGISTRO_DETALLE DROP COLUMN expone2;
ALTER TABLE RWE_REGISTRO_DETALLE DROP COLUMN solicita2;

REINDEX INDEX RWE_REGISTRO_DETALLE_PKEY;

--Cambio de tipo de datos para campos varchar2 de 4000 caracteres
ALTER TABLE RWE_REGISTRO_SIR RENAME COLUMN expone TO expone2;
ALTER TABLE RWE_REGISTRO_SIR RENAME COLUMN solicita TO solicita2;

ALTER TABLE RWE_REGISTRO_SIR ADD expone text;
ALTER TABLE RWE_REGISTRO_SIR ADD solicita text;

UPDATE RWE_REGISTRO_SIR SET expone=expone2;
UPDATE RWE_REGISTRO_SIR SET solicita=solicita2;
ALTER TABLE RWE_REGISTRO_SIR DROP COLUMN expone2;
ALTER TABLE RWE_REGISTRO_SIR DROP COLUMN solicita2;

REINDEX INDEX RWE_REGISTRO_SIR_PKEY;

