--Nuevo campo Expediente en la tabla RWE_REGISTRO_DETALLE
ALTER TABLE RWE_REGISTRO_DETALLE add (EXPEDIENTE_JUST varchar2(256 char));

--Modificar tamaño campos tipo RAW Tabla RWE_ANEXO
ALTER TABLE RWE_ANEXO MODIFY HASH raw(2000);
ALTER TABLE RWE_ANEXO MODIFY CERTIFICADO raw(2000);
ALTER TABLE RWE_ANEXO MODIFY VAL_OCSP_CERTIFICADO raw(2000);
ALTER TABLE RWE_ANEXO MODIFY TIMESTAMP raw(2000);
ALTER TABLE RWE_ANEXO MODIFY FIRMA raw(2000);