--Nuevo campo RWE_REGISTRO_DETALLE
alter table RWE_REGISTRO_DETALLE add RECIBIDO_SIR bool NOT NULL DEFAULT FALSE;

--Nuevo campos en RWE_OFICIOI_REMISION
ALTER TABLE RWE_OFICIO_REMISION add DEC_T_ANOTACION varchar(80);
ALTER TABLE RWE_OFICIO_REMISION add TIPO_ANOTACION  varchar(2);
