--Nuevo campo RWE_REGISTRO_DETALLE
ALTER TABLE RWE_REGISTRO_DETALLE add APLICACION_TELEMATICA varchar2(255 char);

--Nuevos campos en RWE_ANEXO
ALTER TABLE RWE_ANEXO add CONFIDENCIAL bool DEFAULT false not null;
ALTER TABLE RWE_ANEXO add NOMBRE_FICHERO varchar2(255 char);
ALTER TABLE RWE_ANEXO add TAMANO_FICHERO number(10,0);



