package es.caib.regweb3.persistence.utils.sir;
//
//This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
//See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
//Any modifications to this file will be lost upon recompilation of the source schema. 
//Generated on: 2014.07.28 at 11:58:40 AM CEST 
//

import javax.xml.bind.annotation.XmlRegistry;


/**
* This object contains factory methods for each 
* Java content interface and Java element interface 
* generated in the es.caib.regweb3.persistence.utils package.
* <p>An FicheroIntercambioSICRES3Factory allows you to programatically 
* construct new instances of the Java representation 
* for XML content. The Java representation of XML 
* content can consist of schema derived interfaces 
* and classes representing the binding of schema 
* type definitions, element declarations and model 
* groups.  Factory methods for each of these are 
* provided in this class.
* 
*/
@XmlRegistry
public class FicheroIntercambioSICRES3Factory {


 /**
  * Create a new FicheroIntercambioSICRES3Factory that can be used to create new instances of schema derived classes for package: es.caib.regweb3.persistence.utils
  * 
  */
 public FicheroIntercambioSICRES3Factory() {
 }

 /**
  * Create an instance of {@link FicheroIntercambioSICRES3 .DeInteresado }
  * 
  */
 public FicheroIntercambioSICRES3.DeInteresado createFicheroIntercambioSICRES3DeInteresado() {
     return new FicheroIntercambioSICRES3.DeInteresado();
 }

 /**
  * Create an instance of {@link FicheroIntercambioSICRES3 .DeAnexo }
  * 
  */
 public FicheroIntercambioSICRES3.DeAnexo createFicheroIntercambioSICRES3DeAnexo() {
     return new FicheroIntercambioSICRES3 .DeAnexo();
 }

 /**
  * Create an instance of {@link FicheroIntercambioSICRES3 .DeDestino }
  * 
  */
 public FicheroIntercambioSICRES3 .DeDestino createFicheroIntercambioSICRES3DeDestino() {
     return new FicheroIntercambioSICRES3 .DeDestino();
 }

 /**
  * Create an instance of {@link FicheroIntercambioSICRES3 .DeInternosControl }
  * 
  */
 public FicheroIntercambioSICRES3 .DeInternosControl createFicheroIntercambioSICRES3DeInternosControl() {
     return new FicheroIntercambioSICRES3 .DeInternosControl();
 }

 /**
  * Create an instance of {@link FicheroIntercambioSICRES3 .DeOrigenORemitente }
  * 
  */
 public FicheroIntercambioSICRES3 .DeOrigenORemitente createFicheroIntercambioSICRES3DeOrigenORemitente() {
     return new FicheroIntercambioSICRES3 .DeOrigenORemitente();
 }

 /**
  * Create an instance of {@link FicheroIntercambioSICRES3 .DeFormularioGenerico }
  * 
  */
 public FicheroIntercambioSICRES3 .DeFormularioGenerico createFicheroIntercambioSICRES3DeFormularioGenerico() {
     return new FicheroIntercambioSICRES3 .DeFormularioGenerico();
 }

 /**
  * Create an instance of {@link FicheroIntercambioSICRES3 .DeAsunto }
  * 
  */
 public FicheroIntercambioSICRES3 .DeAsunto createFicheroIntercambioSICRES3DeAsunto() {
     return new FicheroIntercambioSICRES3 .DeAsunto();
 }

 /**
  * Create an instance of {@link FicheroIntercambioSICRES3 }
  * 
  */
 public FicheroIntercambioSICRES3 createFicheroIntercambioSICRES3() {
     return new FicheroIntercambioSICRES3();
 }

}
