--Nuevo campo RWE_REGISTRO_DETALLE
ALTER TABLE RWE_REGISTRO_DETALLE add (RECIBIDO_SIR number(1,0) DEFAULT 0 not null);

--Nuevos campos en RWE_OFICIO_REMISION
ALTER TABLE RWE_OFICIO_REMISION add DEC_T_ANOTACION varchar2(80 char);
ALTER TABLE RWE_OFICIO_REMISION add TIPO_ANOTACION  varchar2(2 char);


