
package org.plugin.geiser.api.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IRegistroWebService", targetNamespace = "http://registro.ws.rgeco.geiser.minhap.gob.es/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IRegistroWebService {


    /**
     * 
     * @param peticion
     * @param authentication
     * @return
     *     returns org.plugin.geiser.api.ws.ResultadoRegistroType
     */
    @WebMethod
    @WebResult(name = "ResultadoRegistroType", targetNamespace = "")
    @RequestWrapper(localName = "registrarEnviarHastaUnidad", targetNamespace = "http://registro.ws.rgeco.geiser.minhap.gob.es/", className = "org.plugin.geiser.api.ws.RegistrarEnviarHastaUnidad")
    @ResponseWrapper(localName = "registrarEnviarHastaUnidadResponse", targetNamespace = "http://registro.ws.rgeco.geiser.minhap.gob.es/", className = "org.plugin.geiser.api.ws.RegistrarEnviarHastaUnidadResponse")
    public ResultadoRegistroType registrarEnviarHastaUnidad(
        @WebParam(name = "authentication", targetNamespace = "")
        AuthenticationType authentication,
        @WebParam(name = "peticion", targetNamespace = "")
        PeticionRegistroEnvioType peticion);

    /**
     * 
     * @param peticion
     * @param authentication
     * @return
     *     returns org.plugin.geiser.api.ws.ResultadoRegistroType
     */
    @WebMethod
    @WebResult(name = "ResultadoRegistroType", targetNamespace = "")
    @RequestWrapper(localName = "registrar", targetNamespace = "http://registro.ws.rgeco.geiser.minhap.gob.es/", className = "org.plugin.geiser.api.ws.Registrar")
    @ResponseWrapper(localName = "registrarResponse", targetNamespace = "http://registro.ws.rgeco.geiser.minhap.gob.es/", className = "org.plugin.geiser.api.ws.RegistrarResponse")
    public ResultadoRegistroType registrar(
        @WebParam(name = "authentication", targetNamespace = "")
        AuthenticationType authentication,
        @WebParam(name = "peticion", targetNamespace = "")
        PeticionRegistroType peticion);

    /**
     * 
     * @param peticion
     * @param authentication
     * @return
     *     returns org.plugin.geiser.api.ws.ResultadoCambioEstadoType
     */
    @WebMethod
    @WebResult(name = "ResultadoCambioEstadoType", targetNamespace = "")
    @RequestWrapper(localName = "confirmar", targetNamespace = "http://registro.ws.rgeco.geiser.minhap.gob.es/", className = "org.plugin.geiser.api.ws.Confirmar")
    @ResponseWrapper(localName = "confirmarResponse", targetNamespace = "http://registro.ws.rgeco.geiser.minhap.gob.es/", className = "org.plugin.geiser.api.ws.ConfirmarResponse")
    public ResultadoCambioEstadoType confirmar(
        @WebParam(name = "authentication", targetNamespace = "")
        AuthenticationType authentication,
        @WebParam(name = "peticion", targetNamespace = "")
        PeticionCambioEstadoType peticion);

    /**
     * 
     * @param peticion
     * @param authentication
     * @return
     *     returns org.plugin.geiser.api.ws.ResultadoCambioEstadoType
     */
    @WebMethod
    @WebResult(name = "ResultadoCambioEstadoType", targetNamespace = "")
    @RequestWrapper(localName = "rechazar", targetNamespace = "http://registro.ws.rgeco.geiser.minhap.gob.es/", className = "org.plugin.geiser.api.ws.Rechazar")
    @ResponseWrapper(localName = "rechazarResponse", targetNamespace = "http://registro.ws.rgeco.geiser.minhap.gob.es/", className = "org.plugin.geiser.api.ws.RechazarResponse")
    public ResultadoCambioEstadoType rechazar(
        @WebParam(name = "authentication", targetNamespace = "")
        AuthenticationType authentication,
        @WebParam(name = "peticion", targetNamespace = "")
        PeticionCambioEstadoType peticion);

    /**
     * 
     * @param uidIterator
     * @param authentication
     * @return
     *     returns org.plugin.geiser.api.ws.ResultadoBusquedaType
     */
    @WebMethod
    @WebResult(name = "ResultadoBusquedaType", targetNamespace = "")
    @RequestWrapper(localName = "iterar", targetNamespace = "http://registro.ws.rgeco.geiser.minhap.gob.es/", className = "org.plugin.geiser.api.ws.Iterar")
    @ResponseWrapper(localName = "iterarResponse", targetNamespace = "http://registro.ws.rgeco.geiser.minhap.gob.es/", className = "org.plugin.geiser.api.ws.IterarResponse")
    public ResultadoBusquedaType iterar(
        @WebParam(name = "authentication", targetNamespace = "")
        AuthenticationType authentication,
        @WebParam(name = "uidIterator", targetNamespace = "")
        String uidIterator);

    /**
     * 
     * @param peticion
     * @param authentication
     * @return
     *     returns org.plugin.geiser.api.ws.ResultadoConsultaType
     */
    @WebMethod
    @WebResult(name = "ResultadoConsultaType", targetNamespace = "")
    @RequestWrapper(localName = "consultar", targetNamespace = "http://registro.ws.rgeco.geiser.minhap.gob.es/", className = "org.plugin.geiser.api.ws.Consultar")
    @ResponseWrapper(localName = "consultarResponse", targetNamespace = "http://registro.ws.rgeco.geiser.minhap.gob.es/", className = "org.plugin.geiser.api.ws.ConsultarResponse")
    public ResultadoConsultaType consultar(
        @WebParam(name = "authentication", targetNamespace = "")
        AuthenticationType authentication,
        @WebParam(name = "peticion", targetNamespace = "")
        PeticionConsultaType peticion);

    /**
     * 
     * @param peticion
     * @param authentication
     * @return
     *     returns org.plugin.geiser.api.ws.ResultadoBusquedaEstadoTramitacionType
     */
    @WebMethod
    @WebResult(name = "ResultadoBusquedaEstadoTramitacionType", targetNamespace = "")
    @RequestWrapper(localName = "buscarEstadoTramitacion", targetNamespace = "http://registro.ws.rgeco.geiser.minhap.gob.es/", className = "org.plugin.geiser.api.ws.BuscarEstadoTramitacion")
    @ResponseWrapper(localName = "buscarEstadoTramitacionResponse", targetNamespace = "http://registro.ws.rgeco.geiser.minhap.gob.es/", className = "org.plugin.geiser.api.ws.BuscarEstadoTramitacionResponse")
    public ResultadoBusquedaEstadoTramitacionType buscarEstadoTramitacion(
        @WebParam(name = "authentication", targetNamespace = "")
        AuthenticationType authentication,
        @WebParam(name = "peticion", targetNamespace = "")
        PeticionBusquedaEstadoTramitacionType peticion);

    /**
     * 
     * @param peticion
     * @param authentication
     * @return
     *     returns org.plugin.geiser.api.ws.ResultadoBusquedaType
     */
    @WebMethod
    @WebResult(name = "ResultadoBusquedaType", targetNamespace = "")
    @RequestWrapper(localName = "buscar", targetNamespace = "http://registro.ws.rgeco.geiser.minhap.gob.es/", className = "org.plugin.geiser.api.ws.Buscar")
    @ResponseWrapper(localName = "buscarResponse", targetNamespace = "http://registro.ws.rgeco.geiser.minhap.gob.es/", className = "org.plugin.geiser.api.ws.BuscarResponse")
    public ResultadoBusquedaType buscar(
        @WebParam(name = "authentication", targetNamespace = "")
        AuthenticationType authentication,
        @WebParam(name = "peticion", targetNamespace = "")
        PeticionBusquedaType peticion);

    /**
     * 
     * @param peticion
     * @param authentication
     * @return
     *     returns org.plugin.geiser.api.ws.ResultadoRegistroType
     */
    @WebMethod
    @WebResult(name = "ResultadoRegistroType", targetNamespace = "")
    @RequestWrapper(localName = "registrarEnviar", targetNamespace = "http://registro.ws.rgeco.geiser.minhap.gob.es/", className = "org.plugin.geiser.api.ws.RegistrarEnviar")
    @ResponseWrapper(localName = "registrarEnviarResponse", targetNamespace = "http://registro.ws.rgeco.geiser.minhap.gob.es/", className = "org.plugin.geiser.api.ws.RegistrarEnviarResponse")
    public ResultadoRegistroType registrarEnviar(
        @WebParam(name = "authentication", targetNamespace = "")
        AuthenticationType authentication,
        @WebParam(name = "peticion", targetNamespace = "")
        PeticionRegistroEnvioSimpleType peticion);

}
