
package org.plugin.geiser.api.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RegistroWebService", targetNamespace = "http://ws.rgeco.geiser.minhap.gob.es/", wsdlLocation = "file:/C:/Jamalj/regweb-geiser/git/registre/plugins/plugin-geiser/plugin-geiser-api/wsdl/RegistroWebService.wsdl")
public class RegistroWebService
    extends Service
{

    private final static URL REGISTROWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException REGISTROWEBSERVICE_EXCEPTION;
    private final static QName REGISTROWEBSERVICE_QNAME = new QName("http://ws.rgeco.geiser.minhap.gob.es/", "RegistroWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Jamalj/regweb-geiser/git/registre/plugins/plugin-geiser/plugin-geiser-api/wsdl/RegistroWebService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        REGISTROWEBSERVICE_WSDL_LOCATION = url;
        REGISTROWEBSERVICE_EXCEPTION = e;
    }

    public RegistroWebService() {
        super(__getWsdlLocation(), REGISTROWEBSERVICE_QNAME);
    }

    public RegistroWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), REGISTROWEBSERVICE_QNAME, features);
    }

    public RegistroWebService(URL wsdlLocation) {
        super(wsdlLocation, REGISTROWEBSERVICE_QNAME);
    }

    public RegistroWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, REGISTROWEBSERVICE_QNAME, features);
    }

    public RegistroWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RegistroWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IRegistroWebService
     */
    @WebEndpoint(name = "RegistroWebServicePort")
    public IRegistroWebService getRegistroWebServicePort() {
        return super.getPort(new QName("http://ws.rgeco.geiser.minhap.gob.es/", "RegistroWebServicePort"), IRegistroWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IRegistroWebService
     */
    @WebEndpoint(name = "RegistroWebServicePort")
    public IRegistroWebService getRegistroWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.rgeco.geiser.minhap.gob.es/", "RegistroWebServicePort"), IRegistroWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (REGISTROWEBSERVICE_EXCEPTION!= null) {
            throw REGISTROWEBSERVICE_EXCEPTION;
        }
        return REGISTROWEBSERVICE_WSDL_LOCATION;
    }

}
