--Nuevos campos RWE_ORGANISMO
ALTER TABLE RWE_ORGANISMO add (confidencial number(1,0) DEFAULT 0 not null);

--Nuevos campos RWE_USUARIO_ENTIDAD
ALTER TABLE RWE_USUARIO_ENTIDAD add CERTIFICADO number(19,0);
ALTER TABLE RWE_USUARIO_ENTIDAD add constraint RWE_USUENT_CERTIFICADO_FK foreign key (CERTIFICADO) references RWE_ARCHIVO;
ALTER TABLE RWE_USUARIO_ENTIDAD ADD FECHA_CERTIFICADO timestamp;

--Unique Key RWE_PERSONA
ALTER TABLE RWE_PERSONA ADD CONSTRAINT RWE_PERSONA_DOC_ENT_UK UNIQUE (DOCUMENTO, ENTIDAD);
