--Nuevos campos RWE_ORGANISMO
ALTER TABLE RWE_ORGANISMO add (confidencial number(1,0) DEFAULT 0 not null);

--Nuevos campos RWE_USUARIO_ENTIDAD
ALTER TABLE RWE_USUARIO_ENTIDAD add CERTIFICADO number(19,0);
ALTER TABLE RWE_USUARIO_ENTIDAD add constraint RWE_USUENT_CERTIFICADO_FK foreign key (CERTIFICADO) references RWE_ARCHIVO;
ALTER TABLE RWE_USUARIO_ENTIDAD ADD FECHA_CERTIFICADO timestamp;

--Unique Key RWE_PERSONA
ALTER TABLE RWE_PERSONA ADD CONSTRAINT RWE_PERSONA_DOC_ENT_UK UNIQUE (DOCUMENTO, ENTIDAD);

--Cambio de nombre de un campo en RWE_USUARIO_ENTIDAD
ALTER TABLE RWE_USUARIO_ENTIDAD rename column ULTIMAOFICINA TO OFICINA_SOLICITADA;

-- Secuencias específicas para los Registros Migrados
create sequence RWE_REGISTRO_MIGRADO_SEQ start with 1 increment by  1;
create sequence RWE_REGISTRO_LOPD_MIGRADO_SEQ start with 1 increment by  1;
create sequence RWE_MODIFICACION_LOPD_MIGRADO_SEQ start with 1 increment by  1;

ALTER TABLE RWE_REGISTRO_MIGRADO MODIFY PRODESGEO NULL;

--Nuevo campo RWE_TRAZABILIDAD
ALTER TABLE RWE_TRAZABILIDAD add OBSERVACIONES varchar2(2000 char);

--Modificaciones campos RWE_DESCARGA
ALTER TABLE RWE_DESCARGA DROP COLUMN FECHAINICIO;
ALTER TABLE RWE_DESCARGA DROP COLUMN FECHAFIN;
ALTER TABLE RWE_DESCARGA ADD (ELEMENTOS CLOB);
ALTER TABLE RWE_DESCARGA RENAME COLUMN tipo TO tipo2;
ALTER TABLE RWE_DESCARGA ADD TIPO number(10,0);
UPDATE RWE_DESCARGA set tipo = 1 where tipo2='unidad';
UPDATE RWE_DESCARGA set tipo = 2 where tipo2='oficina';
UPDATE RWE_DESCARGA set tipo = 3 where tipo2='catalogo';
ALTER TABLE RWE_DESCARGA DROP COLUMN tipo2;

--Modificaciones campos RWE_REGISTRO_MIGRADO
alter table RWE_REGISTRO_MIGRADO MODIFY FECHADOC null;
alter table RWE_REGISTRO_MIGRADO MODIFY DESCDOC null;
alter table RWE_REGISTRO_MIGRADO MODIFY DESIDIDOC null;

--Modificacion de campo RWE_INTERESADO
ALTER TABLE RWE_INTERESADO MODIFY DOCUMENTO VARCHAR2(256 CHAR);
-- Modificación de campo DOCUMENTO en RWE_PERSONA
ALTER TABLE RWE_PERSONA MODIFY DOCUMENTO VARCHAR2(256 CHAR);
