ALTER TABLE RWE_REGISTRO_ENTRADA MODIFY FECHA NULL;
ALTER TABLE RWE_REGISTRO_ENTRADA MODIFY NUMREGFORMAT NULL;

--CAMBIO TIPO COLUMNA NUMREGISTRO
ALTER TABLE RWE_REGISTRO_ENTRADA ADD NUMREGISTRO_TMP NUMBER(10);
UPDATE RWE_REGISTRO_ENTRADA SET NUMREGISTRO_TMP = NUMREGISTRO;
ALTER TABLE RWE_REGISTRO_ENTRADA MODIFY NUMREGISTRO NULL;
UPDATE RWE_REGISTRO_ENTRADA SET NUMREGISTRO = NULL;

ALTER TABLE RWE_REGISTRO_ENTRADA MODIFY NUMREGISTRO VARCHAR2(20 CHAR);
UPDATE RWE_REGISTRO_ENTRADA SET NUMREGISTRO = NUMREGISTRO_TMP;
ALTER TABLE RWE_REGISTRO_ENTRADA DROP COLUMN NUMREGISTRO_TMP;

ALTER TABLE RWE_REGISTRO_SALIDA MODIFY FECHA NULL;
ALTER TABLE RWE_REGISTRO_SALIDA MODIFY NUMREGFORMAT NULL;

--CAMBIO TIPO COLUMNA NUMREGISTRO
ALTER TABLE RWE_REGISTRO_SALIDA ADD NUMREGISTRO_TMP NUMBER(10);
UPDATE RWE_REGISTRO_SALIDA SET NUMREGISTRO_TMP = NUMREGISTRO;
ALTER TABLE RWE_REGISTRO_SALIDA MODIFY NUMREGISTRO NULL;
UPDATE RWE_REGISTRO_SALIDA SET NUMREGISTRO = NULL;
ALTER TABLE RWE_REGISTRO_SALIDA MODIFY NUMREGISTRO VARCHAR2(20 CHAR);
UPDATE RWE_REGISTRO_SALIDA SET NUMREGISTRO = NUMREGISTRO_TMP;
ALTER TABLE RWE_REGISTRO_SALIDA DROP COLUMN NUMREGISTRO_TMP;

--CAMBIO TIPO COLUMNA NUMREG_ORIGEN
ALTER TABLE RWE_REGISTRO_DETALLE ADD NUMREG_ORIGEN_TMP VARCHAR2(20 CHAR);
UPDATE RWE_REGISTRO_DETALLE SET NUMREG_ORIGEN_TMP = NUMREG_ORIGEN;
UPDATE RWE_REGISTRO_DETALLE SET NUMREG_ORIGEN = NULL;
ALTER TABLE RWE_REGISTRO_DETALLE MODIFY NUMREG_ORIGEN VARCHAR2(20 CHAR);
UPDATE RWE_REGISTRO_DETALLE SET NUMREG_ORIGEN = NUMREG_ORIGEN_TMP;
ALTER TABLE RWE_REGISTRO_DETALLE DROP COLUMN NUMREG_ORIGEN_TMP;

ALTER TABLE RWE_LOPD ADD NUMREGISTRO_TMP NUMBER(10);
UPDATE RWE_LOPD SET NUMREGISTRO_TMP = NUMREGISTRO;
ALTER TABLE RWE_LOPD MODIFY NUMREGISTRO NULL;
UPDATE RWE_LOPD SET NUMREGISTRO = NULL;
ALTER TABLE RWE_LOPD MODIFY NUMREGISTRO VARCHAR2(255 CHAR);
UPDATE RWE_LOPD SET NUMREGISTRO = NUMREGISTRO_TMP;
ALTER TABLE RWE_LOPD DROP COLUMN NUMREGISTRO_TMP;


ALTER TABLE RWE_LOPD MODIFY ANYOREGISTRO NULL;

ALTER TABLE RWE_REGISTRO_SIR ADD DOCUMENTO_USUARIO VARCHAR2(17 CHAR);
ALTER TABLE RWE_REGISTRO_SIR MODIFY ID_INTERCAMBIO NULL;

-- Nuevo Contador para genera el Identificador Intercambio SIR, realizar tantos inserts como Entidades haya creadas, indicado su id
INSERT into RWE_CONTADOR (id, numero) VALUES (RWE_ALL_SEQ.nextVal,0);
UPDATE RWE_ENTIDAD set CONTADOR_SIR=RWE_ALL_SEQ.currval where id=?;

-- Identificar documento firma dettached (no disponible identificador intercanvi fins que s'envia a GEISER)
ALTER TABLE RWE_ANEXO_SIR ADD DOCUMENTO NUMBER(19) NULL;
ALTER TABLE RWE_ANEXO_SIR
        ADD CONSTRAINT RWE_DOCUMENTOSIR_ANEXO_FK
        FOREIGN KEY (DOCUMENTO)
        REFERENCES RWE_ANEXO_SIR;
        
-- Borrar formato número registro (ahora el número se obtiene de GEISER)
UPDATE RWE_ENTIDAD SET NUMREGISTRO = NULL;

ALTER TABLE RWE_REGISTRO_SIR MODIFY APLICACION VARCHAR2(10 CHAR);
ALTER TABLE RWE_TRAZABILIDAD_SIR MODIFY APLICACION VARCHAR2(10 CHAR);

-- Campo necesario para consultar identificador intercambio registros recibidos
ALTER TABLE RWE_REGISTRO_SIR ADD NUMERO_REGISTRO_ORIGEN VARCHAR2(20 CHAR);

ALTER TABLE RWE_ANEXO_SIR MODIFY TIPO_MIME VARCHAR2(50 CHAR);

-- Cron modificable 
INSERT INTO RWE_PROPIEDADGLOBAL (ID, CLAVE, DESCRIPCION, ENTIDAD, TIPO, VALOR) VALUES (RWE_ALL_SEQ.nextVal,'es.caib.regweb3.cron.actualizacion.envio.sir.periodo','Tiempo inicial actualización registros enviados vía SIR',null,1,600000); --10min
INSERT INTO RWE_PROPIEDADGLOBAL (ID, CLAVE, DESCRIPCION, ENTIDAD, TIPO, VALOR) VALUES (RWE_ALL_SEQ.nextVal,'es.caib.regweb3.cron.actualizacion.envio.sir.retardo','Retardo entre cada actualización registros enviados vía SIR',null,1,600000); --10min

-- Cron modificable
INSERT INTO RWE_PROPIEDADGLOBAL (ID, CLAVE, DESCRIPCION, ENTIDAD, TIPO, VALOR) VALUES (RWE_ALL_SEQ.nextVal,'es.caib.regweb3.cron.actualizacion.envio.recibido.sir.periodo','Tiempo inicial actualización registros recibidos vía SIR',null,1,600000); --10min
INSERT INTO RWE_PROPIEDADGLOBAL (ID, CLAVE, DESCRIPCION, ENTIDAD, TIPO, VALOR) VALUES (RWE_ALL_SEQ.nextVal,'es.caib.regweb3.cron.actualizacion.envio.recibido.sir.retardo','Retardo entre cada actualización registros recibidos vía SIR',null,1,600000); --10min

-- Cron modificable
INSERT INTO RWE_PROPIEDADGLOBAL (ID, CLAVE, DESCRIPCION, ENTIDAD, TIPO, VALOR) VALUES (RWE_ALL_SEQ.nextVal,'es.caib.regweb3.cron.actualizacion.id.envio.recibido.sir.periodo','Tiempo inicial actualización registros enviados vía SIR',null,1,900000); --15min
INSERT INTO RWE_PROPIEDADGLOBAL (ID, CLAVE, DESCRIPCION, ENTIDAD, TIPO, VALOR) VALUES (RWE_ALL_SEQ.nextVal,'es.caib.regweb3.cron.actualizacion.id.envio.recibido.sir.retardo','Tiempo inicial actualización registros enviados vía SIR',null,1,900000); --15min


ALTER TABLE RWE_REGISTRO_DETALLE add (JUSTIFICANTE_GEISER NUMBER(1,0) DEFAULT 0 NOT NULL);