	<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	
	<parent>
		<groupId>es.caib.regweb3</groupId>
		<artifactId>regweb3-plugins</artifactId>
		<version>3.2.4</version>
	</parent>
	
	<artifactId>plugin-custodia</artifactId>

	<repositories>
		<repository>
			<id>github-governib-maven-repos</id>
			<name>GitHub GovernIB Maven Repository</name>
			<url>http://GovernIB.github.io/maven/maven/</url>
		</repository>
	</repositories>
	<properties>
	   <maven.compiler.source>1.7</maven.compiler.source>
	   <maven.compiler.target>1.7</maven.compiler.target>
	   <pluginsib-validatesignature-afirmacxf.version>2.0.7</pluginsib-validatesignature-afirmacxf.version>
	</properties>
	<dependencies>
		<dependency>
		      <groupId>org.fundaciobit.pluginsib.validatesignature</groupId>
		      <artifactId>pluginsib-validatesignature-api</artifactId>
		      <version>2.0.6</version>
		      <scope>provided</scope>
	    </dependency>
		
		<dependency>
	     	<groupId>org.fundaciobit.pluginsib.validatesignature</groupId>
	      	<artifactId>pluginsib-validatesignature-afirmacxf</artifactId>
	      	<version>${pluginsib-validatesignature-afirmacxf.version}</version>
			<scope>provided</scope>
	        <exclusions>
	          	<exclusion>
	          		<groupId>xerces</groupId>
	          		<artifactId>xercesImpl</artifactId>
	        	</exclusion>
	
		        <exclusion>
		         	 <groupId>com.sun.xml.bind</groupId>
		          	<artifactId>jaxb-impl</artifactId>
		        </exclusion>
		
		        <exclusion>
		         	 <groupId>xalan</groupId>
		         	 <artifactId>xalan</artifactId>
		        </exclusion>
		
		        <exclusion>
		         	 <groupId>org.slf4j</groupId>
		         	 <artifactId>log4j-over-slf4j</artifactId>
		        </exclusion>
		
		        <exclusion>
		         	 <groupId>org.slf4j</groupId>
		         	 <artifactId>jcl-over-slf4j</artifactId>
		        </exclusion>
		
		         <exclusion>
		         	 <groupId>org.apache.ws.security</groupId>
		        	  <artifactId>wss4j</artifactId>
		        </exclusion>
	      </exclusions>
    </dependency>
    
		<dependency>
	      <groupId>org.fundaciobit.pluginsib.documentcustody</groupId>
	      <artifactId>pluginsib-documentcustody-api</artifactId>
	      <version>4.0.0</version>
	      <scope>provided</scope>
	    </dependency>
    
		<dependency>
			<groupId>org.freemarker</groupId>
			<artifactId>freemarker</artifactId>
			<version>2.3.23</version>
		</dependency>
	
		<dependency>
			<groupId>log4j</groupId>
			<artifactId>log4j</artifactId>
			<version>1.2.17</version>
		</dependency>
	
		<!-- Distribució -->
		<dependency>
			<groupId>com.sun.jersey</groupId>
			<artifactId>jersey-client</artifactId>
			<version>1.19</version>
		</dependency>
	
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
			<version>2.6.3</version>
		</dependency>
	
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-core</artifactId>
			<version>2.6.0</version>
		</dependency>
	
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
			<version>2.6.0</version>
		</dependency>
	
		<dependency>
			<groupId>commons-codec</groupId>
			<artifactId>commons-codec</artifactId>
			<version>1.9</version>
		</dependency>
	
		<!-- -->
		<dependency>
			<groupId>wsdl4j</groupId>
			<artifactId>wsdl4j</artifactId>
			<version>1.6.2</version>
		</dependency>
	 	
		<dependency>
			<groupId>org.apache.axis</groupId>
			<artifactId>axis</artifactId>
			<version>1.4</version>
			<scope>provided</scope>
		</dependency>
	
		<dependency>
			<groupId>axis</groupId>
			<artifactId>axis-jaxrpc</artifactId>
			<version>1.4</version>
			<scope>provided</scope>
		</dependency>
		
		<dependency>
			<groupId>org.bouncycastle</groupId>
      		<artifactId>bcprov-jdk15on</artifactId>
			<version>1.51</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.bouncycastle</groupId>
      		<artifactId>bcmail-jdk15on</artifactId>
			<version>1.51</version>
			<scope>provided</scope>
		</dependency>
	    <!--  -->
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<version>1.5.6</version>
		</dependency>
		
		<!-- Obtenció documents desde site -->
		<dependency>
			<groupId>commons-io</groupId>
			<artifactId>commons-io</artifactId>
			<version>2.2</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.alfresco.cmis.client</groupId>
			<artifactId>alfresco-opencmis-extension</artifactId>
			<version>1.0</version>
		</dependency>
		<dependency>
			<groupId>com.google.oauth-client</groupId>
			<artifactId>google-oauth-client</artifactId>
			<version>1.16.0-rc</version>
			<exclusions>
				<exclusion>
					<artifactId>xpp3</artifactId>
					<groupId>xpp3</groupId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>com.google.http-client</groupId>
			<artifactId>google-http-client-jackson</artifactId>
			<version>1.16.0-rc</version>
		</dependency>
		<dependency>
		 	<groupId>org.alfresco.client</groupId> 
		 	<artifactId>alfresco-java-client</artifactId> 
		 	<version>1.0.0-beta1</version> 
		 	<exclusions>
		 		<exclusion>
		 			<groupId>com.squareup.okhttp3</groupId>
    				<artifactId>okhttp</artifactId>
		 		</exclusion>
		 	</exclusions>
		</dependency>
		<dependency>
		    <groupId>com.squareup.okhttp3</groupId>
		    <artifactId>okhttp</artifactId>
		    <version>3.0.1</version>
		</dependency>	
		<dependency>
		    <groupId>com.sun.jersey</groupId>
		    <artifactId>jersey-client</artifactId>
		    <version>1.19.4</version>
		</dependency>

		<!-- test
		-->
		<dependency>
		    <groupId>com.syncthemall</groupId>
		    <artifactId>boilerpipe</artifactId>
		    <version>1.2.1</version>
		    <scope>test</scope>
		</dependency>
		<dependency>
		    <groupId>org.apache.cxf</groupId>
		    <artifactId>cxf-rt-frontend-jaxws</artifactId>
		    <version>2.2.12</version>
		    <scope>test</scope>
		</dependency>
		<dependency>
		    <groupId>org.apache.cxf</groupId>
		    <artifactId>cxf-rt-transports-http-jetty</artifactId>
		    <version>2.2.12</version>
		    <scope>test</scope>
		</dependency>
		<dependency>
		    <groupId>org.apache.cxf</groupId>
		    <artifactId>cxf-rt-ws-security</artifactId>
		    <version>2.2.12</version>
		    <scope>test</scope>
		    <exclusions>
		    	<exclusion>
		    		<groupId>org.bouncycastle</groupId>
           			<artifactId>bcprov-jdk15</artifactId>
		    	</exclusion>
		    	<exclusion>
		    		<groupId>org.apache.santuario</groupId>
					<artifactId>xmlsec</artifactId>
		    	</exclusion>
		    </exclusions>
		</dependency>
		<dependency>
			<groupId>org.apache.santuario</groupId>
			<artifactId>xmlsec</artifactId>
			<version>1.4.2</version>
			<scope>test</scope>
		</dependency>
		<!--
		<dependency>
			<groupId>org.fundaciobit.plugins</groupId>
			<artifactId>plugins-api</artifactId>
			<version>1.0.0</version>
		</dependency>
		-->
		<dependency>
            <groupId>org.fundaciobit.pluginsib.core</groupId>
            <artifactId>pluginsib-core</artifactId>
            <version>2.0.0</version>
            <scope>provided</scope>
        </dependency>
         
	</dependencies>



	<build>
		<plugins>
			<plugin>
				<artifactId>maven-deploy-plugin</artifactId>
				<version>2.8.1</version>
				<configuration>
					<altDeploymentRepository>
						internal.repo::default::file://${project.build.directory}/mvn-repo
					</altDeploymentRepository>
				</configuration>
			</plugin>

			<plugin>
				<groupId>com.github.github</groupId>
				<artifactId>site-maven-plugin</artifactId>
				<version>0.12</version>
				<configuration>
					<!-- git commit message -->
					<message>Maven artifacts for ${project.version}</message>
					<outputDirectory>${project.build.directory}/mvn-repo</outputDirectory>
					<noJekyll>true</noJekyll>
					<!-- remote branch name -->
					<branch>refs/heads/gh-pages</branch>
					<includes>
						<include>**/*</include>
					</includes>
					<path>maven</path>
					<!-- github repo name -->
					<repositoryName>maven</repositoryName>
					<!-- github username or organization -->
					<repositoryOwner>GovernIB</repositoryOwner>
					<server>github_governib_maven</server>
					<merge>true</merge>
					<dryRun>false</dryRun>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>site</goal>
						</goals>
						<phase>deploy</phase>
					</execution>
				</executions>
			</plugin>
			
			<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.2</version>
            </plugin>
		</plugins>
	</build>

	<distributionManagement>
		<repository>
			<id>github_governib_maven</id>
			<name>GitHub GovernIB Maven Repository</name>
			<url>file://${project.build.directory}/mvn-repo</url>
		</repository>
	</distributionManagement>


	<!-- COM UTILITZAR: AFEGIR AQUEST CODI AL pom.xml -->
	<!-- <repositories> <repository> <id>github-governib-maven-repos</id> <name>GitHub 
		GovernIB Maven Repository</name> <url>http://GovernIB.github.io/maven/maven/</url> 
		</repository> </repositories> -->

</project>