-- ANEXO NUEVOS CAMPOS SICRES4
alter table RWE_ANEXO add CODFORMUL varchar2(80 char);
alter table RWE_ANEXO add RESUMEN varchar2(160 char);
alter table RWE_ANEXO add ENDPOINTRFU varchar2(255 char);
alter table RWE_ANEXO add IDENTIFRFU varchar2(255 char);

--Cambio tamanyo ANEXOSIR
ALTER TABLE RWE_ANEXO_SIR MODIFY OBSERVACIONES varchar2(160 char);

--Campos eliminados ANEXOSIR
ALTER TABLE RWE_ANEXO_SIR DROP COLUMN CERTIFICADO CASCADE CONSTRAINT;
ALTER TABLE RWE_ANEXO_SIR DROP COLUMN FIRMA CASCADE CONSTRAINT;
ALTER TABLE RWE_ANEXO_SIR DROP COLUMN HASH CASCADE CONSTRAINT;
ALTER TABLE RWE_ANEXO_SIR DROP COLUMN TIMESTAMP CASCADE CONSTRAINT;
ALTER TABLE RWE_ANEXO_SIR DROP COLUMN VAL_OCSP_CE CASCADE CONSTRAINT;
ALTER TABLE RWE_ANEXO_SIR DROP COLUMN VALIDEZ_DOCUMENTO CASCADE CONSTRAINT;

--Nueva tabla METADATO
create table RWE_METADATO (
      ID number(19,0) not null,
      CAMPO varchar2(80 char),
      VALOR varchar2(255 char),
      ANEXOGENERAL number(19,0),
      ANEXOPARTICULAR number(19,0),
      REGDETGEN number(19,0),
      REGDETPART number(19,0),
      primary key (ID)
);

alter table RWE_METADATO
    add constraint RWE_METADATO_ANEXGEN_FK
        foreign key (ANEXOGENERAL)
            references RWE_ANEXO;

alter table RWE_METADATO
    add constraint RWE_METADATO_ANEXPART_FK
        foreign key (ANEXOPARTICULAR)
            references RWE_ANEXO;

alter table RWE_METADATO
    add constraint RWE_METADATO_REGDETGEN_FK
        foreign key (REGDETGEN)
            references RWE_REGISTRO_DETALLE;

alter table RWE_METADATO
    add constraint RWE_METADATO_REGDETPART_FK
        foreign key (REGDETPART)
            references RWE_REGISTRO_DETALLE;

-- Cambios tamanyo RegistroDetalle
ALTER TABLE RWE_REGISTRO_DETALLE MODIFY NUMTRANSPORTE varchar2(40 char);
ALTER TABLE RWE_REGISTRO_DETALLE MODIFY OBSERVACIONES varchar2(160 char);
ALTER TABLE RWE_REGISTRO_DETALLE MODIFY DEC_T_ANOTACION varchar2(160 char);
ALTER TABLE RWE_REGISTRO_DETALLE MODIFY DEC_ENT_REG_DEST varchar2(120 char);

-- Paso a not null
update RWE_REGISTRO_DETALLE set INDICADOR_PRUEBA=0 where INDICADOR_PRUEBA is null;
ALTER TABLE RWE_REGISTRO_DETALLE MODIFY (INDICADOR_PRUEBA number(10,0) not null);

-- Campos nuevos RegistroDetalle
-- Actualización de campo nuevo not null;
UPDATE RWE_REGISTRO_DETALLE
SET FECHA_PRES_INTER = (
    SELECT fecha
    FROM rwe_registro_entrada
    WHERE rwe_registro_entrada.REGISTRO_DETALLE = RWE_REGISTRO_DETALLE.ID
);

alter table RWE_REGISTRO_DETALLE add FECHA_PRES_INTER timestamp;
UPDATE RWE_REGISTRO_DETALLE
SET FECHA_PRES_INTER = (
    SELECT fecha
    FROM rwe_registro_entrada
    WHERE rwe_registro_entrada.REGISTRO_DETALLE = RWE_REGISTRO_DETALLE.ID
);
ALTER TABLE RWE_REGISTRO_DETALLE MODIFY ( FECHA_PRES_INTER NOT NULL);
alter table RWE_REGISTRO_DETALLE add TIMESTAMP_PRES_INTER varchar2(255 char);
alter table RWE_REGISTRO_DETALLE add IDINTERCAMBIO_PREVIO varchar2(33 char);
alter table RWE_REGISTRO_DETALLE add COD_UNITRAM_INICIO varchar2(21 char);
alter table RWE_REGISTRO_DETALLE add DEC_UNITRAM_INICIO varchar2(120 char);

--Cambios tamanyo RegistroSir
ALTER TABLE RWE_REGISTRO_SIR MODIFY DEC_ENT_REG_ORI varchar2(120 char);
ALTER TABLE RWE_REGISTRO_SIR MODIFY DEC_ENT_REG_DEST varchar2(120 char);
ALTER TABLE RWE_REGISTRO_SIR MODIFY DEC_UNI_TRA_DEST varchar2(120 char);
ALTER TABLE RWE_REGISTRO_SIR MODIFY OBSERVACIONES varchar2(160 char);
ALTER TABLE RWE_REGISTRO_SIR MODIFY DEC_ENT_REG_INI varchar2(120 char);

--
ALTER TABLE RWE_TRAZABILIDAD_SIR MODIFY DEC_ENT_REG_ORI varchar2(120 char);
ALTER TABLE RWE_TRAZABILIDAD_SIR MODIFY DEC_ENT_REG_DEST varchar2(120 char);
ALTER TABLE RWE_TRAZABILIDAD_SIR MODIFY DEC_UNI_TRA_DEST varchar2(120 char);
ALTER TABLE RWE_TRAZABILIDAD_SIR MODIFY APLICACION varchar2(20 char);


--Eliminar campos de Interesado
ALTER TABLE RWE_INTERESADO DROP COLUMN DIRELECTRONICA CASCADE CONSTRAINT;

--Nuevos campos Interesado
alter table RWE_INTERESADO add RECEPNOTIF number(1,0);
alter table RWE_INTERESADO add TLFMOVIL varchar2(20 char);
alter table RWE_INTERESADO add DIRUNIFICADO varchar2(21 char);
alter table RWE_INTERESADO add AVISONOTIFEMAIL number(1,0);
alter table RWE_INTERESADO add AVISONOTIFSMS number(1,0);



