-- Nuevos campos en RWE_REGISTRO_DETALLE PARA FUNCIONARIOS HABILITADOS
ALTER TABLE RWE_REGISTRO_DETALLE add  CODIGO_FUNC_HAB VARCHAR2(256 CHAR);
ALTER TABLE RWE_REGISTRO_DETALLE add  NOMBRE_FUNC_HAB VARCHAR2(512 CHAR);
ALTER TABLE RWE_REGISTRO_DETALLE add  NIF_FUNC_HAB VARCHAR2(256 CHAR);
