--Adaptacio nova arquitectura SIR
alter table RWE_REGISTRO_DETALLE add CODIGOSIA int8;
alter table RWE_REGISTRO_DETALLE add PRESENCIAL bool;
alter table RWE_REGISTRO_DETALLE add TIPOENVIODOC varchar(2);
alter table RWE_INTERESADO add CODIGODIRE varchar(15);

--Nuevo ROLES de Usuario WS
ALTER TABLE RWE_USUARIO add RWE_WS_ENTRADA int8 DEFAULT 1 not null;
ALTER TABLE RWE_USUARIO add RWE_WS_SALIDA int8 DEFAULT 1 not null;
ALTER TABLE RWE_USUARIO add RWE_WS_CIUDADANO int8 DEFAULT 1 not null;
