<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>es.caib.regweb3</groupId>
        <artifactId>regweb3</artifactId>
        <version>3.3.5</version>
    </parent>

    <artifactId>regweb3-integraciones</artifactId>
    <version>3.3.5</version>
    <packaging>jar</packaging>

    <name>RegWeb3 - Integraciones</name>

    <properties>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>

        <dependency>
            <groupId>es.caib.regweb3</groupId>
            <artifactId>regweb3-model</artifactId>
        </dependency>

        <dependency>
            <groupId>org.fundaciobit.genapp</groupId>
            <artifactId>genapp-core</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <scope>provided</scope>
        </dependency>

        <!-- Spring -->
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-webmvc</artifactId>
            <scope>provided</scope>
        </dependency>

    </dependencies>

</project>