
package org.plugin.lema.api.realizadas.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GDRealizadasWsService", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/lema/1.0/", wsdlLocation = "file:/home/jamal/projects/registre-apb/registre-geiser/plugins/plugin-lema/plugin-lema-api/wsdl/realizadas.wsdl")
public class GDRealizadasWsService
    extends Service
{

    private final static URL GDREALIZADASWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException GDREALIZADASWSSERVICE_EXCEPTION;
    private final static QName GDREALIZADASWSSERVICE_QNAME = new QName("https://administracionelectronica.gob.es/notifica/ws/lema/1.0/", "GDRealizadasWsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/jamal/projects/registre-apb/registre-geiser/plugins/plugin-lema/plugin-lema-api/wsdl/realizadas.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GDREALIZADASWSSERVICE_WSDL_LOCATION = url;
        GDREALIZADASWSSERVICE_EXCEPTION = e;
    }

    public GDRealizadasWsService() {
        super(__getWsdlLocation(), GDREALIZADASWSSERVICE_QNAME);
    }

    public GDRealizadasWsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GDREALIZADASWSSERVICE_QNAME, features);
    }

    public GDRealizadasWsService(URL wsdlLocation) {
        super(wsdlLocation, GDREALIZADASWSSERVICE_QNAME);
    }

    public GDRealizadasWsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GDREALIZADASWSSERVICE_QNAME, features);
    }

    public GDRealizadasWsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GDRealizadasWsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GDRealizadasWsPortType
     */
    @WebEndpoint(name = "GDRealizadasWsPort")
    public GDRealizadasWsPortType getGDRealizadasWsPort() {
        return super.getPort(new QName("https://administracionelectronica.gob.es/notifica/ws/lema/1.0/", "GDRealizadasWsPort"), GDRealizadasWsPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GDRealizadasWsPortType
     */
    @WebEndpoint(name = "GDRealizadasWsPort")
    public GDRealizadasWsPortType getGDRealizadasWsPort(WebServiceFeature... features) {
        return super.getPort(new QName("https://administracionelectronica.gob.es/notifica/ws/lema/1.0/", "GDRealizadasWsPort"), GDRealizadasWsPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GDREALIZADASWSSERVICE_EXCEPTION!= null) {
            throw GDREALIZADASWSSERVICE_EXCEPTION;
        }
        return GDREALIZADASWSSERVICE_WSDL_LOCATION;
    }

}
