
package org.plugin.lema.api.realizadas.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GDRealizadasWsPortType", targetNamespace = "https://administracionelectronica.gob.es/notifica/ws/lema/1.0/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GDRealizadasWsPortType {


    /**
     * 
     * @param localizaRealizadas
     * @return
     *     returns org.plugin.lema.api.realizadas.ws.RespuestaLocalizaRealizadas
     */
    @WebMethod(operationName = "LocalizaRealizadas", action = "https://administracionelectronica.gob.es/notifica/ws/lema/LocalizaRealizadas")
    @WebResult(name = "RespuestaLocalizaRealizadas", targetNamespace = "http://administracion.gob.es/punto-unico-notificaciones/localizaRealizadas", partName = "RespuestaLocalizaRealizadas")
    public RespuestaLocalizaRealizadas localizaRealizadas(
        @WebParam(name = "LocalizaRealizadas", targetNamespace = "http://administracion.gob.es/punto-unico-notificaciones/localizaRealizadas", partName = "LocalizaRealizadas")
        LocalizaRealizadas localizaRealizadas);

    /**
     * 
     * @param consultaRealizadas
     * @return
     *     returns org.plugin.lema.api.realizadas.ws.RespuestaConsultaRealizadas
     */
    @WebMethod(operationName = "ConsultaRealizadas", action = "https://administracionelectronica.gob.es/notifica/ws/lema/ConsultaRealizadas")
    @WebResult(name = "RespuestaConsultaRealizadas", targetNamespace = "http://administracion.gob.es/punto-unico-notificaciones/consultaRealizadas", partName = "RespuestaConsultaRealizadas")
    public RespuestaConsultaRealizadas consultaRealizadas(
        @WebParam(name = "ConsultaRealizadas", targetNamespace = "http://administracion.gob.es/punto-unico-notificaciones/consultaRealizadas", partName = "ConsultaRealizadas")
        ConsultaRealizadas consultaRealizadas);

}
