-- ANEXO NUEVOS CAMPOS SICRES4
alter table RWE_ANEXO add CODFORMUL varchar2(80 char);
alter table RWE_ANEXO add RESUMEN varchar2(160 char);
alter table RWE_ANEXO add ENDPOINTRFU varchar2(255 char);
alter table RWE_ANEXO add IDENTIFRFU varchar2(4000 char);

--Cambio tamanyo RWE_ANEXO_SIR
ALTER TABLE RWE_ANEXO_SIR MODIFY OBSERVACIONES varchar2(160 char);

--Cambio a  null del campo hash en RWE_ANEXO_SIR
ALTER TABLE RWE_ANEXO_SIR MODIFY HASH NULL;

--Nuevas tablas metadatos
create table RWE_METADATO_ANEXO (
   ID number(19,0) not null,
    CAMPO varchar2(80 char),
    TIPO number(19,0),
    VALOR varchar2(4000 char),
    ANEXO number(19,0),
    primary key (ID)
);

create table RWE_METADATO_REGENT (
   ID number(19,0) not null,
    CAMPO varchar2(80 char),
    TIPO number(19,0),
    VALOR varchar2(4000 char),
    REGISTRO_ENTRADA number(19,0),
    primary key (ID)
);

create table RWE_METADATO_REGSAL (
   ID number(19,0) not null,
    CAMPO varchar2(80 char),
    TIPO number(19,0),
    VALOR varchar2(4000 char),
    REGISTRO_SALIDA number(19,0),
    primary key (ID)
);

 alter table RWE_METADATO_ANEXO
   add constraint RWE_METANEX_ANEXO_FK
   foreign key (ANEXO)
   references RWE_ANEXO;

alter table RWE_METADATO_REGENT
   add constraint RWE_METAREN_REGENT_FK
   foreign key (REGISTRO_ENTRADA)
   references RWE_REGISTRO_ENTRADA;

alter table RWE_METADATO_REGSAL
   add constraint RWE_METRSAL_REGSAL_FK
   foreign key (REGISTRO_SALIDA)
   references RWE_REGISTRO_SALIDA;

-- Cambios tamanyo RWE_REGISTRO_DETALLE
ALTER TABLE RWE_REGISTRO_DETALLE MODIFY NUMTRANSPORTE varchar2(40 char);
ALTER TABLE RWE_REGISTRO_DETALLE MODIFY OBSERVACIONES varchar2(160 char);
ALTER TABLE RWE_REGISTRO_DETALLE MODIFY DEC_T_ANOTACION varchar2(160 char);
ALTER TABLE RWE_REGISTRO_DETALLE MODIFY DEC_ENT_REG_DEST varchar2(120 char);

--Cambios tamanyo RWE_REGISTRO_SIR
ALTER TABLE RWE_REGISTRO_SIR MODIFY DEC_ENT_REG_ORI varchar2(120 char);
ALTER TABLE RWE_REGISTRO_SIR MODIFY DEC_ENT_REG_DEST varchar2(120 char);
ALTER TABLE RWE_REGISTRO_SIR MODIFY DEC_UNI_TRA_DEST varchar2(120 char);
ALTER TABLE RWE_REGISTRO_SIR MODIFY OBSERVACIONES varchar2(160 char);
ALTER TABLE RWE_REGISTRO_SIR MODIFY DEC_ENT_REG_INI varchar2(120 char);
ALTER TABLE RWE_REGISTRO_SIR MODIFY DEC_UNI_TRA_ORI varchar2(120 char);

-- Modificaciones en RWE_TRAZABILIDAD_SIR
ALTER TABLE RWE_TRAZABILIDAD_SIR MODIFY DEC_ENT_REG_ORI varchar2(120 char);
ALTER TABLE RWE_TRAZABILIDAD_SIR MODIFY DEC_ENT_REG_DEST varchar2(120 char);
ALTER TABLE RWE_TRAZABILIDAD_SIR MODIFY DEC_UNI_TRA_DEST varchar2(120 char);
ALTER TABLE RWE_TRAZABILIDAD_SIR MODIFY APLICACION varchar2(20 char);

-- Nuevos campos RWE_INTERESADO
alter table RWE_INTERESADO add RECEPNOTIF number(1,0);
alter table RWE_INTERESADO add TLFMOVIL varchar2(20 char);
alter table RWE_INTERESADO add AVISONOTIFEMAIL number(1,0);
alter table RWE_INTERESADO add AVISONOTIFSMS number(1,0);

-- Renombrado CODIGODIRE en RWE_INTERESADO
alter table RWE_INTERESADO rename column CODIGODIRE TO CODDIRUNIF;
ALTER TABLE RWE_INTERESADO MODIFY CODDIRUNIF varchar2(21 char);

--Nuevos campos RWE_REGISTRO_SIR
ALTER TABLE RWE_REGISTRO_SIR ADD  CODIGO_SIA varchar2(80 char);
ALTER TABLE RWE_REGISTRO_SIR ADD  COD_UNI_TRA_INI varchar2(21 char) ;
ALTER TABLE RWE_REGISTRO_SIR ADD  DEC_UNI_TRA_INI varchar2(120 char);
ALTER TABLE RWE_REGISTRO_SIR ADD  FECHA_REGISTRO_PRESENTACION timestamp;
update RWE_REGISTRO_SIR set FECHA_REGISTRO_PRESENTACION=FECHAR_EGISTRO;
ALTER TABLE RWE_REGISTRO_SIR MODIFY (FECHA_REGISTRO_PRESENTACION timestamp not null);
ALTER TABLE RWE_REGISTRO_SIR ADD  MODO_REGISTRO varchar2(1 char);
ALTER TABLE RWE_REGISTRO_SIR ADD  REFERENCIA_UNICA number(1,0);

--Campos Modificados RWE_REGISTRO_SIR
ALTER TABLE RWE_REGISTRO_SIR MODIFY APLICACION varchar2(20 char);
ALTER TABLE RWE_REGISTRO_SIR MODIFY DEC_T_ANOTACION varchar2(160 char);

--Nuevos campos RWE_INTERESADO_SIR
ALTER TABLE RWE_INTERESADO_SIR ADD COD_DIR_UNIF_INTERESADO varchar2(21 char);
ALTER TABLE RWE_INTERESADO_SIR ADD COD_DIR_UNIF_REPRESENTANTE varchar2(21 char);
ALTER TABLE RWE_INTERESADO_SIR ADD RECEP_NOTIF_INTERESADO number(1,0);
ALTER TABLE RWE_INTERESADO_SIR ADD RECEP_NOTIF_REPRESENTANTE number(1,0);
ALTER TABLE RWE_INTERESADO_SIR ADD NOTIF_EMAIL_INTERESADO number(1,0);
ALTER TABLE RWE_INTERESADO_SIR ADD NOTIF_EMAIL_REPRESENTANTE number(1,0);
ALTER TABLE RWE_INTERESADO_SIR ADD NOTIF_SMS_INTERESADO number(1,0);
ALTER TABLE RWE_INTERESADO_SIR ADD NOTIF_SMS_REPRESENTANTE number(1,0);
ALTER TABLE RWE_INTERESADO_SIR ADD TELEFONO_MOVIL_INTERESADO varchar2(20 char);
ALTER TABLE RWE_INTERESADO_SIR ADD TELEFONO_MOVIL_REPRESENTANTE varchar2(20 char);

--Nuevos campos RWE_ANEXO_SIR
ALTER TABLE RWE_ANEXO_SIR ADD COD_FORMULARIO varchar2(80 char);
ALTER TABLE RWE_ANEXO_SIR ADD RESUMEN varchar2(160 char);
ALTER TABLE RWE_ANEXO_SIR ADD URL_REPOSITORIO varchar2(1000 char);
ALTER TABLE RWE_ANEXO_SIR ADD TIPO_FIRMA varchar2(5 char);
ALTER TABLE RWE_ANEXO_SIR ADD CSV varchar2(512 char);
ALTER TABLE RWE_ANEXO_SIR ADD REGULACION_CSV varchar2(2000 char);
ALTER TABLE RWE_ANEXO_SIR ADD REFERENCIA_FIRMA varchar2(255 char);
ALTER TABLE RWE_ANEXO_SIR ADD FIRMA_BASE64 long;

--Nuevas tablas de metadatos
create table RWE_METADATO_REGSIR (
    ID number(19,0) not null,
    CAMPO varchar2(80 char),
    TIPO number(19,0),
    VALOR varchar2(4000 char),
    REGISTRO_SIR number(19,0) not null,
    primary key (ID)
);
alter table RWE_METADATO_REGSIR
       add constraint RWE_METARSIR_REGSIR_FK
       foreign key (REGISTRO_SIR)
       references RWE_REGISTRO_SIR;

create table RWE_METADATO_ANEXO_SIR (
    ID number(19,0) not null,
    CAMPO varchar2(80 char),
    TIPO number(19,0),
    VALOR varchar2(4000 char),
    ANEXO_SIR number(19,0) not null,
    primary key (ID)
);

alter table RWE_METADATO_ANEXO_SIR
        add constraint RWE_METANEX_ANEXOSIR_FK
        foreign key (ANEXO_SIR)
        references RWE_ANEXO_SIR;

--Nuevas secuencias
create sequence RWE_MTDRESIR_SEQ start with 1 increment by  1;
create sequence RWE_MTDANSIR_SEQ start with 1 increment by  1;
create sequence RWE_MTDRE_SEQ start with 1 increment by  1;
create sequence RWE_MTDRS_SEQ start with 1 increment by  1;
create sequence RWE_MTDAN_SEQ start with 1 increment by  1;

--Transformar codigoSIA de númerico a alfanúmerico
ALTER TABLE RWE_REGISTRO_DETALLE ADD (CODIGOSIA_temp  VARCHAR2(80 char));
update RWE_REGISTRO_DETALLE set CODIGOSIA_temp = CODIGOSIA;
ALTER TABLE RWE_REGISTRO_DETALLE DROP COLUMN CODIGOSIA;
ALTER TABLE RWE_REGISTRO_DETALLE RENAME COLUMN CODIGOSIA_temp TO CODIGOSIA;

--Nuevos campos RWE_PERSONA
alter table RWE_PERSONA add RECEPNOTIF number(1,0);
alter table RWE_PERSONA add TLFMOVIL varchar2(20 char);
alter table RWE_PERSONA add AVISONOTIFEMAIL number(1,0);
alter table RWE_PERSONA add AVISONOTIFSMS number(1,0);
ALTER TABLE RWE_PERSONA add CODDIRUNIF varchar2(21 char);

--Nuevo campo ENTIDAD en RWE_PENDIENTE
alter table RWE_PENDIENTE add ENTIDAD number(19,0);
alter table RWE_PENDIENTE add constraint RWE_PENDIE_ENTIDAD_FK foreign key (ENTIDAD) references RWE_ENTIDAD;

--Nuevo campo EXTERNO en RWE_ORGANISMO
ALTER TABLE RWE_ORGANISMO ADD EXTERNO number(1,0) DEFAULT 0;

--Nuevo índice en la tabla RWE_INTERESADO
create index RWE_INTERES_REGDET_FK_I on RWE_INTERESADO (REGISTRODETALLE);

--Nuevo campo en RWE_OFICINA
ALTER TABLE RWE_OFICINA ADD ACTIVALIBSIR number(1,0) DEFAULT 0;

--Nuevo campo en RWE_REGISTRO_SIR
ALTER TABLE RWE_REGISTRO_SIR ADD LIBSIR number(1,0) DEFAULT 0;

--Eliminar campo RWE_USUARIO_ENTIDAD OAMR
ALTER TABLE RWE_USUARIO_ENTIDAD drop column OAMR;

--Nuevos campos RWE_USUARIO_ENTIDAD
ALTER TABLE RWE_USUARIO_ENTIDAD add CATEGORIA number(19,0);
ALTER TABLE RWE_USUARIO_ENTIDAD add FUNCION number(19,0);
ALTER TABLE RWE_USUARIO_ENTIDAD add TELEFONO varchar2(255 char);
ALTER TABLE RWE_USUARIO_ENTIDAD add CAI number(10,0);
ALTER TABLE RWE_USUARIO_ENTIDAD add NOMBRETRABAJO varchar2(255 char);
ALTER TABLE RWE_USUARIO_ENTIDAD add CODIGOTRABAJO varchar2(255 char);
ALTER TABLE RWE_USUARIO_ENTIDAD add OBSERVACIONES varchar2(255 char);
ALTER TABLE RWE_USUARIO_ENTIDAD add (clave number(1,0) DEFAULT 0 not null);
ALTER TABLE RWE_USUARIO_ENTIDAD add (bitcita number(1,0) DEFAULT 0 not null);
ALTER TABLE RWE_USUARIO_ENTIDAD add (asistencia number(1,0) DEFAULT 0 not null);
ALTER TABLE RWE_USUARIO_ENTIDAD add (apodera number(1,0) DEFAULT 0 not null);
ALTER TABLE RWE_USUARIO_ENTIDAD add (notificacion number(1,0) DEFAULT 0 not null);
ALTER TABLE RWE_USUARIO_ENTIDAD ADD FECHAALTA timestamp;

--Nueva tabla RWE_CATISLA
CREATE TABLE RWE_CATISLA (
                             ID number(19,0) not null,
                             CODIGOISLA number(19,0) not null,
                             DESCRIPCIONISLA varchar2(50 char) not null,
                             PROVINCIA number(19,0)
);
ALTER TABLE RWE_CATISLA add constraint RWE_CATISLA_pk primary key (ID);
ALTER TABLE RWE_CATISLA add constraint RWE_CATISLA_CATPROVIN_FK foreign key (PROVINCIA) references RWE_CATPROVINCIA;
CREATE INDEX RWE_CATISL_CATPRO_FK_I on RWE_CATISLA (PROVINCIA) TABLESPACE REGWEB_INDEX;

--Nuevos campos RWE_OFICINA
ALTER TABLE RWE_OFICINA add (OAMR number(1,0) DEFAULT 0 not null);
ALTER TABLE RWE_OFICINA add ISLA number(19,0);
ALTER TABLE RWE_OFICINA add constraint RWE_OFICINA_ISLA_FK foreign key (ISLA) references RWE_CATISLA;
CREATE INDEX RWE_OFICIN_ISLA_FK_I on RWE_OFICINA (ISLA) TABLESPACE REGWEB_INDEX;

--Nuevo campo RWE_ORGANISMO
ALTER TABLE RWE_ORGANISMO add ISLA number(19,0);
ALTER TABLE RWE_ORGANISMO add constraint RWE_ORGANISMO_ISLA_FK foreign key (ISLA) references RWE_CATISLA;
CREATE INDEX RWE_ORGANI_ISLA_FK_I on RWE_ORGANISMO (ISLA) TABLESPACE REGWEB_INDEX;

-- Índice RWE_ANEXO
CREATE INDEX RWE_ANEXO_CUSTID_FK_I on RWE_ANEXO (CUSTODIAID) TABLESPACE REGWEB_INDEX;

--Nuevo campo RWE_ENTIDAD
ALTER TABLE RWE_ENTIDAD add (REG_SALIDAS_PERSONAS number(1,0) DEFAULT 1 not null);
--Eliminar campo RWE_ENTIDAD Oficio Remisión
ALTER TABLE RWE_ENTIDAD drop column OFICIOREMISION;

--Nuevo campo ENTIDAD en RWE_OFICINA
alter table RWE_OFICINA add ENTIDAD number(19,0);
alter table RWE_OFICINA add constraint RWE_OFICINA_ENTIDAD_FK foreign key (ENTIDAD) references RWE_ENTIDAD;


--Nuevas secuencias inicializdas en el valor más grande de la tabla
DECLARE
interesado_id INTEGER;
   anexo_id INTEGER;
   anexoSir_id INTEGER;
   archivo_id INTEGER;
   hre_id INTEGER;
   hrs_id INTEGER;
   interesadoSir_id INTEGER;
   lopd_id INTEGER;
   notificacion_id INTEGER;
   oficina_id INTEGER;
   oficio_id INTEGER;
   organismo_id INTEGER;
   persona_id INTEGER;
   registroDetalle_id INTEGER;
   registroEntrada_id INTEGER;
   registroSalida_id INTEGER;
   registroSir_id INTEGER;
   trazabilidad_id INTEGER;
   trazabilidadSir_id INTEGER;
   usuario_id INTEGER;
   usuarioEntidad_id INTEGER;

BEGIN
SELECT MAX (id) INTO interesado_id FROM RWE_INTERESADO; interesado_id := interesado_id + 1;
SELECT MAX (id) INTO anexo_id FROM RWE_ANEXO; anexo_id := anexo_id + 1;
SELECT MAX (id) INTO anexoSir_id FROM RWE_ANEXO_SIR; anexoSir_id := anexoSir_id + 1;
SELECT MAX (id) INTO archivo_id FROM RWE_ARCHIVO; archivo_id := archivo_id + 1;
SELECT MAX (id) INTO hre_id FROM RWE_HISTORICO_REGISTRO_ENTRADA; hre_id := hre_id + 1;
SELECT MAX (id) INTO hrs_id FROM RWE_HISTORICO_REGISTRO_SALIDA; hrs_id := hrs_id + 1;
SELECT MAX (id) INTO interesadoSir_id FROM RWE_INTERESADO_SIR; interesadoSir_id := interesadoSir_id + 1;
SELECT MAX (id) INTO lopd_id FROM RWE_LOPD; lopd_id := lopd_id + 1;
SELECT MAX (id) INTO notificacion_id FROM RWE_NOTIFICACION; notificacion_id := notificacion_id + 1;
SELECT MAX (id) INTO oficina_id FROM RWE_OFICINA; oficina_id := oficina_id + 1;
SELECT MAX (id) INTO oficio_id FROM RWE_OFICIO_REMISION; oficio_id := oficio_id + 1;
SELECT MAX (id) INTO organismo_id FROM RWE_ORGANISMO; organismo_id := organismo_id + 1;
SELECT MAX (id) INTO persona_id FROM RWE_PERSONA; persona_id := persona_id + 1;
SELECT MAX (id) INTO registroDetalle_id FROM RWE_REGISTRO_DETALLE; registroDetalle_id := registroDetalle_id + 1;
SELECT MAX (id) INTO registroEntrada_id FROM RWE_REGISTRO_ENTRADA; registroEntrada_id := registroEntrada_id + 1;
SELECT MAX (id) INTO registroSalida_id FROM RWE_REGISTRO_SALIDA; registroSalida_id := registroSalida_id + 1;
SELECT MAX (id) INTO registroSir_id FROM RWE_REGISTRO_SIR; registroSir_id := registroSir_id + 1;
SELECT MAX (id) INTO trazabilidad_id FROM RWE_TRAZABILIDAD; trazabilidad_id := trazabilidad_id + 1;
SELECT MAX (id) INTO trazabilidadSir_id FROM RWE_TRAZABILIDAD_SIR; trazabilidadSir_id := trazabilidadSir_id + 1;
SELECT MAX (id) INTO usuario_id FROM RWE_USUARIO; usuario_id := usuario_id + 1;
SELECT MAX (id) INTO usuarioEntidad_id FROM RWE_USUARIO_ENTIDAD; usuarioEntidad_id := usuarioEntidad_id + 1;

EXECUTE IMMEDIATE 'CREATE SEQUENCE RWE_INTERESADO_SEQ START WITH ' || interesado_id || ' INCREMENT BY 1';
EXECUTE IMMEDIATE 'CREATE SEQUENCE RWE_ANEXO_SEQ START WITH ' || anexo_id || ' INCREMENT BY 1';
EXECUTE IMMEDIATE 'CREATE SEQUENCE RWE_ANEXOSIR_SEQ START WITH ' || anexoSir_id || ' INCREMENT BY 1';
EXECUTE IMMEDIATE 'CREATE SEQUENCE RWE_ARCHIVO_SEQ START WITH ' || archivo_id || ' INCREMENT BY 1';
EXECUTE IMMEDIATE 'CREATE SEQUENCE RWE_HRE_SEQ START WITH ' || hre_id || ' INCREMENT BY 1';
EXECUTE IMMEDIATE 'CREATE SEQUENCE RWE_HRS_SEQ START WITH ' || hrs_id || ' INCREMENT BY 1';
EXECUTE IMMEDIATE 'CREATE SEQUENCE RWE_INTERESADOSIR_SEQ START WITH ' || interesadoSir_id || ' INCREMENT BY 1';
EXECUTE IMMEDIATE 'CREATE SEQUENCE RWE_LOPD_SEQ START WITH ' || lopd_id || ' INCREMENT BY 1';
EXECUTE IMMEDIATE 'CREATE SEQUENCE RWE_NOTIFICACION_SEQ START WITH ' || notificacion_id || ' INCREMENT BY 1';
EXECUTE IMMEDIATE 'CREATE SEQUENCE RWE_OFICINA_SEQ START WITH ' || oficina_id || ' INCREMENT BY 1';
EXECUTE IMMEDIATE 'CREATE SEQUENCE RWE_OFICIOREMISION_SEQ START WITH ' || oficio_id || ' INCREMENT BY 1';
EXECUTE IMMEDIATE 'CREATE SEQUENCE RWE_ORGANISMO_SEQ START WITH ' || organismo_id || ' INCREMENT BY 1';
EXECUTE IMMEDIATE 'CREATE SEQUENCE RWE_PERSONA_SEQ START WITH ' || persona_id || ' INCREMENT BY 1';
EXECUTE IMMEDIATE 'CREATE SEQUENCE RWE_REGISTRODETALLE_SEQ START WITH ' || registroDetalle_id || ' INCREMENT BY 1';
EXECUTE IMMEDIATE 'CREATE SEQUENCE RWE_REGISTROENTRADA_SEQ START WITH ' || registroEntrada_id || ' INCREMENT BY 1';
EXECUTE IMMEDIATE 'CREATE SEQUENCE RWE_REGISTROSALIDA_SEQ START WITH ' || registroSalida_id || ' INCREMENT BY 1';
EXECUTE IMMEDIATE 'CREATE SEQUENCE RWE_REGISTROSIR_SEQ START WITH ' || registroSir_id || ' INCREMENT BY 1';
EXECUTE IMMEDIATE 'CREATE SEQUENCE RWE_TRAZABILIDAD_SEQ START WITH ' || trazabilidad_id || ' INCREMENT BY 1';
EXECUTE IMMEDIATE 'CREATE SEQUENCE RWE_TRAZABILIDADSIR_SEQ START WITH ' || trazabilidadSir_id || ' INCREMENT BY 1';
EXECUTE IMMEDIATE 'CREATE SEQUENCE RWE_USUARIO_SEQ START WITH ' || usuario_id || ' INCREMENT BY 1';
EXECUTE IMMEDIATE 'CREATE SEQUENCE RWE_USUARIOENTIDAD_SEQ START WITH ' || usuarioEntidad_id || ' INCREMENT BY 1';
END;
/

