package es.caib.regweb3.ws.api.v3;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.5.redhat-00001
 * 2023-10-04T12:41:20.805+02:00
 * Generated source version: 3.2.5.redhat-00001
 *
 */
@WebService(targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", name = "RegWebAsientoRegistralWs")
@XmlSeeAlso({ObjectFactory.class})
public interface RegWebAsientoRegistralWs {

    @WebMethod
    @RequestWrapper(localName = "obtenerOficioExterno", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.ObtenerOficioExterno")
    @ResponseWrapper(localName = "obtenerOficioExternoResponse", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.ObtenerOficioExternoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public es.caib.regweb3.ws.api.v3.OficioWs obtenerOficioExterno(
        @WebParam(name = "entidad", targetNamespace = "")
        java.lang.String entidad,
        @WebParam(name = "numeroRegistroFormateado", targetNamespace = "")
        java.lang.String numeroRegistroFormateado
    ) throws WsValidationException, WsI18NException;

    @WebMethod
    @RequestWrapper(localName = "obtenerAsientosCiudadanoCarpeta", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.ObtenerAsientosCiudadanoCarpeta")
    @ResponseWrapper(localName = "obtenerAsientosCiudadanoCarpetaResponse", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.ObtenerAsientosCiudadanoCarpetaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public es.caib.regweb3.ws.api.v3.ResultadoBusquedaWs obtenerAsientosCiudadanoCarpeta(
        @WebParam(name = "entidad", targetNamespace = "")
        java.lang.String entidad,
        @WebParam(name = "documento", targetNamespace = "")
        java.lang.String documento,
        @WebParam(name = "pageNumber", targetNamespace = "")
        java.lang.Integer pageNumber,
        @WebParam(name = "idioma", targetNamespace = "")
        java.lang.String idioma,
        @WebParam(name = "fechaInicio", targetNamespace = "")
        java.sql.Timestamp fechaInicio,
        @WebParam(name = "fechaFin", targetNamespace = "")
        java.sql.Timestamp fechaFin,
        @WebParam(name = "numeroRegistroFormateado", targetNamespace = "")
        java.lang.String numeroRegistroFormateado,
        @WebParam(name = "estados", targetNamespace = "")
        java.util.List<java.lang.Integer> estados,
        @WebParam(name = "extracto", targetNamespace = "")
        java.lang.String extracto,
        @WebParam(name = "resultPorPagina", targetNamespace = "")
        java.lang.Integer resultPorPagina
    ) throws WsValidationException, WsI18NException;

    @WebMethod
    @RequestWrapper(localName = "obtenerAsientoCiudadanoCarpeta", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.ObtenerAsientoCiudadanoCarpeta")
    @ResponseWrapper(localName = "obtenerAsientoCiudadanoCarpetaResponse", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.ObtenerAsientoCiudadanoCarpetaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public es.caib.regweb3.ws.api.v3.AsientoWs obtenerAsientoCiudadanoCarpeta(
        @WebParam(name = "entidad", targetNamespace = "")
        java.lang.String entidad,
        @WebParam(name = "documento", targetNamespace = "")
        java.lang.String documento,
        @WebParam(name = "numeroRegistroFormateado", targetNamespace = "")
        java.lang.String numeroRegistroFormateado,
        @WebParam(name = "idioma", targetNamespace = "")
        java.lang.String idioma
    );

    @WebMethod
    @RequestWrapper(localName = "obtenerAsientosCiudadano", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.ObtenerAsientosCiudadano")
    @ResponseWrapper(localName = "obtenerAsientosCiudadanoResponse", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.ObtenerAsientosCiudadanoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public es.caib.regweb3.ws.api.v3.ResultadoBusquedaWs obtenerAsientosCiudadano(
        @WebParam(name = "entidad", targetNamespace = "")
        java.lang.String entidad,
        @WebParam(name = "documento", targetNamespace = "")
        java.lang.String documento,
        @WebParam(name = "pageNumber", targetNamespace = "")
        java.lang.Integer pageNumber
    ) throws WsValidationException, WsI18NException;

    @WebMethod
    @RequestWrapper(localName = "obtenerSesionRegistro", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.ObtenerSesionRegistro")
    @ResponseWrapper(localName = "obtenerSesionRegistroResponse", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.ObtenerSesionRegistroResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.Long obtenerSesionRegistro(
        @WebParam(name = "entidad", targetNamespace = "")
        java.lang.String entidad
    ) throws WsI18NException;

    @WebMethod
    @RequestWrapper(localName = "distribuirAsientoRegistral", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.DistribuirAsientoRegistral")
    @ResponseWrapper(localName = "distribuirAsientoRegistralResponse", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.DistribuirAsientoRegistralResponse")
    public void distribuirAsientoRegistral(
        @WebParam(name = "entidad", targetNamespace = "")
        java.lang.String entidad,
        @WebParam(name = "numeroRegistroFormateado", targetNamespace = "")
        java.lang.String numeroRegistroFormateado
    ) throws WsValidationException, WsI18NException;

    @WebMethod
    @RequestWrapper(localName = "obtenerJustificante", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.ObtenerJustificante")
    @ResponseWrapper(localName = "obtenerJustificanteResponse", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.ObtenerJustificanteResponse")
    @WebResult(name = "return", targetNamespace = "")
    public es.caib.regweb3.ws.api.v3.JustificanteWs obtenerJustificante(
        @WebParam(name = "entidad", targetNamespace = "")
        java.lang.String entidad,
        @WebParam(name = "numeroRegistroFormateado", targetNamespace = "")
        java.lang.String numeroRegistroFormateado,
        @WebParam(name = "tipoRegistro", targetNamespace = "")
        java.lang.Long tipoRegistro
    ) throws WsValidationException, WsI18NException;

    @WebMethod
    @RequestWrapper(localName = "crearAsientoRegistral", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.CrearAsientoRegistral")
    @ResponseWrapper(localName = "crearAsientoRegistralResponse", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.CrearAsientoRegistralResponse")
    @WebResult(name = "return", targetNamespace = "")
    public es.caib.regweb3.ws.api.v3.AsientoRegistralWs crearAsientoRegistral(
        @WebParam(name = "idSesion", targetNamespace = "")
        java.lang.Long idSesion,
        @WebParam(name = "entidad", targetNamespace = "")
        java.lang.String entidad,
        @WebParam(name = "asientoRegistral", targetNamespace = "")
        es.caib.regweb3.ws.api.v3.AsientoRegistralWs asientoRegistral,
        @WebParam(name = "tipoOperacion", targetNamespace = "")
        java.lang.Long tipoOperacion,
        @WebParam(name = "justificante", targetNamespace = "")
        java.lang.Boolean justificante,
        @WebParam(name = "distribuir", targetNamespace = "")
        java.lang.Boolean distribuir
    ) throws WsValidationException, WsI18NException;

    @WebMethod
    @RequestWrapper(localName = "obtenerAsientoCiudadano", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.ObtenerAsientoCiudadano")
    @ResponseWrapper(localName = "obtenerAsientoCiudadanoResponse", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.ObtenerAsientoCiudadanoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public es.caib.regweb3.ws.api.v3.AsientoRegistralWs obtenerAsientoCiudadano(
        @WebParam(name = "entidad", targetNamespace = "")
        java.lang.String entidad,
        @WebParam(name = "documento", targetNamespace = "")
        java.lang.String documento,
        @WebParam(name = "numeroRegistroFormateado", targetNamespace = "")
        java.lang.String numeroRegistroFormateado
    ) throws WsValidationException, WsI18NException;

    @WebMethod
    @RequestWrapper(localName = "obtenerAnexoCiudadano", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.ObtenerAnexoCiudadano")
    @ResponseWrapper(localName = "obtenerAnexoCiudadanoResponse", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.ObtenerAnexoCiudadanoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public es.caib.regweb3.ws.api.v3.FileContentWs obtenerAnexoCiudadano(
        @WebParam(name = "entidad", targetNamespace = "")
        java.lang.String entidad,
        @WebParam(name = "idAnexo", targetNamespace = "")
        java.lang.Long idAnexo,
        @WebParam(name = "idioma", targetNamespace = "")
        java.lang.String idioma
    );

    @WebMethod
    @RequestWrapper(localName = "obtenerAsientoRegistral", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.ObtenerAsientoRegistral")
    @ResponseWrapper(localName = "obtenerAsientoRegistralResponse", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.ObtenerAsientoRegistralResponse")
    @WebResult(name = "return", targetNamespace = "")
    public es.caib.regweb3.ws.api.v3.AsientoRegistralWs obtenerAsientoRegistral(
        @WebParam(name = "entidad", targetNamespace = "")
        java.lang.String entidad,
        @WebParam(name = "numeroRegistroFormateado", targetNamespace = "")
        java.lang.String numeroRegistroFormateado,
        @WebParam(name = "tipoRegistro", targetNamespace = "")
        java.lang.Long tipoRegistro,
        @WebParam(name = "conAnexos", targetNamespace = "")
        boolean conAnexos
    ) throws WsValidationException, WsI18NException;

    @WebMethod
    @RequestWrapper(localName = "obtenerReferenciaJustificante", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.ObtenerReferenciaJustificante")
    @ResponseWrapper(localName = "obtenerReferenciaJustificanteResponse", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.ObtenerReferenciaJustificanteResponse")
    @WebResult(name = "return", targetNamespace = "")
    public es.caib.regweb3.ws.api.v3.JustificanteReferenciaWs obtenerReferenciaJustificante(
        @WebParam(name = "entidad", targetNamespace = "")
        java.lang.String entidad,
        @WebParam(name = "numeroRegistroFormateado", targetNamespace = "")
        java.lang.String numeroRegistroFormateado
    ) throws WsValidationException, WsI18NException;

    @WebMethod
    @RequestWrapper(localName = "verificarAsientoRegistral", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.VerificarAsientoRegistral")
    @ResponseWrapper(localName = "verificarAsientoRegistralResponse", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.VerificarAsientoRegistralResponse")
    @WebResult(name = "return", targetNamespace = "")
    public es.caib.regweb3.ws.api.v3.AsientoRegistralSesionWs verificarAsientoRegistral(
        @WebParam(name = "entidad", targetNamespace = "")
        java.lang.String entidad,
        @WebParam(name = "idSesion", targetNamespace = "")
        java.lang.Long idSesion
    ) throws WsI18NException;
}
