package es.caib.regweb3.ws.api.v3;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.5.redhat-00001
 * 2023-10-04T12:40:11.988+02:00
 * Generated source version: 3.2.5.redhat-00001
 *
 */
@WebService(targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", name = "RegWebInfoWs")
@XmlSeeAlso({ObjectFactory.class})
public interface RegWebInfoWs {

    @WebMethod
    @RequestWrapper(localName = "listarOrganismos", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.ListarOrganismos")
    @ResponseWrapper(localName = "listarOrganismosResponse", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.ListarOrganismosResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<es.caib.regweb3.ws.api.v3.OrganismoWs> listarOrganismos(
        @WebParam(name = "entidadCodigoDir3", targetNamespace = "")
        java.lang.String entidadCodigoDir3
    ) throws WsI18NException;

    @WebMethod
    @RequestWrapper(localName = "listarLibros", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.ListarLibros")
    @ResponseWrapper(localName = "listarLibrosResponse", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.ListarLibrosResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<es.caib.regweb3.ws.api.v3.LibroWs> listarLibros(
        @WebParam(name = "entidadCodigoDir3", targetNamespace = "")
        java.lang.String entidadCodigoDir3,
        @WebParam(name = "oficinaCodigoDir3", targetNamespace = "")
        java.lang.String oficinaCodigoDir3,
        @WebParam(name = "autorizacion", targetNamespace = "")
        java.lang.Long autorizacion
    ) throws WsI18NException;

    @WebMethod
    @RequestWrapper(localName = "obtenerLibrosOficina", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.ObtenerLibrosOficina")
    @ResponseWrapper(localName = "obtenerLibrosOficinaResponse", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.ObtenerLibrosOficinaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<es.caib.regweb3.ws.api.v3.LibroOficinaWs> obtenerLibrosOficina(
        @WebParam(name = "entidadCodigoDir3", targetNamespace = "")
        java.lang.String entidadCodigoDir3,
        @WebParam(name = "tipoRegistro", targetNamespace = "")
        java.lang.Long tipoRegistro
    ) throws WsI18NException;

    @WebMethod
    @RequestWrapper(localName = "listarLibroOrganismo", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.ListarLibroOrganismo")
    @ResponseWrapper(localName = "listarLibroOrganismoResponse", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.ListarLibroOrganismoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public es.caib.regweb3.ws.api.v3.LibroWs listarLibroOrganismo(
        @WebParam(name = "entidad", targetNamespace = "")
        java.lang.String entidad,
        @WebParam(name = "organismo", targetNamespace = "")
        java.lang.String organismo
    ) throws WsI18NException;

    @WebMethod
    @RequestWrapper(localName = "listarOficinas", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.ListarOficinas")
    @ResponseWrapper(localName = "listarOficinasResponse", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.ListarOficinasResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<es.caib.regweb3.ws.api.v3.OficinaWs> listarOficinas(
        @WebParam(name = "entidadCodigoDir3", targetNamespace = "")
        java.lang.String entidadCodigoDir3,
        @WebParam(name = "autorizacion", targetNamespace = "")
        java.lang.Long autorizacion
    ) throws WsI18NException;

    @WebMethod
    @RequestWrapper(localName = "listarTipoAsunto", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.ListarTipoAsunto")
    @ResponseWrapper(localName = "listarTipoAsuntoResponse", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.ListarTipoAsuntoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<es.caib.regweb3.ws.api.v3.TipoAsuntoWs> listarTipoAsunto(
        @WebParam(name = "entidadCodigoDir3", targetNamespace = "")
        java.lang.String entidadCodigoDir3
    ) throws WsI18NException;

    @WebMethod
    @RequestWrapper(localName = "listarTipoDocumental", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.ListarTipoDocumental")
    @ResponseWrapper(localName = "listarTipoDocumentalResponse", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.ListarTipoDocumentalResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<es.caib.regweb3.ws.api.v3.TipoDocumentalWs> listarTipoDocumental(
        @WebParam(name = "entidadCodigoDir3", targetNamespace = "")
        java.lang.String entidadCodigoDir3
    ) throws WsI18NException;

    @WebMethod
    @RequestWrapper(localName = "getVersion", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.GetVersion")
    @ResponseWrapper(localName = "getVersionResponse", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.GetVersionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getVersion();

    @WebMethod
    @RequestWrapper(localName = "getVersionWs", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.GetVersionWs")
    @ResponseWrapper(localName = "getVersionWsResponse", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.GetVersionWsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int getVersionWs();

    @WebMethod
    @RequestWrapper(localName = "listarCodigoAsunto", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.ListarCodigoAsunto")
    @ResponseWrapper(localName = "listarCodigoAsuntoResponse", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.ListarCodigoAsuntoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<es.caib.regweb3.ws.api.v3.CodigoAsuntoWs> listarCodigoAsunto(
        @WebParam(name = "entidadCodigoDir3", targetNamespace = "")
        java.lang.String entidadCodigoDir3,
        @WebParam(name = "codigoTipoAsunto", targetNamespace = "")
        java.lang.String codigoTipoAsunto
    ) throws WsI18NException;

    @WebMethod
    @RequestWrapper(localName = "obtenerLibrosOficinaUsuario", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.ObtenerLibrosOficinaUsuario")
    @ResponseWrapper(localName = "obtenerLibrosOficinaUsuarioResponse", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.ObtenerLibrosOficinaUsuarioResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<es.caib.regweb3.ws.api.v3.LibroOficinaWs> obtenerLibrosOficinaUsuario(
        @WebParam(name = "entidadCodigoDir3", targetNamespace = "")
        java.lang.String entidadCodigoDir3,
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "tipoRegistro", targetNamespace = "")
        java.lang.Long tipoRegistro
    ) throws WsI18NException;
}
