package es.caib.regweb3.ws.api.v3;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.5.redhat-00001
 * 2023-10-04T12:41:09.180+02:00
 * Generated source version: 3.2.5.redhat-00001
 *
 */
@WebService(targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", name = "RegWebRegistroSalidaWs")
@XmlSeeAlso({ObjectFactory.class})
public interface RegWebRegistroSalidaWs {

    @WebMethod
    @RequestWrapper(localName = "obtenerJustificante", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.ObtenerJustificante")
    @ResponseWrapper(localName = "obtenerJustificanteResponse", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.ObtenerJustificanteResponse")
    @WebResult(name = "return", targetNamespace = "")
    public es.caib.regweb3.ws.api.v3.JustificanteWs obtenerJustificante(
        @WebParam(name = "entidad", targetNamespace = "")
        java.lang.String entidad,
        @WebParam(name = "numeroRegistroFormateado", targetNamespace = "")
        java.lang.String numeroRegistroFormateado
    ) throws WsValidationException, WsI18NException;

    @WebMethod
    @RequestWrapper(localName = "obtenerRegistroSalidaID", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.ObtenerRegistroSalidaID")
    @ResponseWrapper(localName = "obtenerRegistroSalidaIDResponse", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.ObtenerRegistroSalidaIDResponse")
    @WebResult(name = "return", targetNamespace = "")
    public es.caib.regweb3.ws.api.v3.IdentificadorWs obtenerRegistroSalidaID(
        @WebParam(name = "any", targetNamespace = "")
        int any,
        @WebParam(name = "numeroRegistro", targetNamespace = "")
        int numeroRegistro,
        @WebParam(name = "libro", targetNamespace = "")
        java.lang.String libro,
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "entidad", targetNamespace = "")
        java.lang.String entidad
    ) throws WsI18NException;

    @WebMethod
    @RequestWrapper(localName = "nuevoRegistroSalida", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.NuevoRegistroSalida")
    @ResponseWrapper(localName = "nuevoRegistroSalidaResponse", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.NuevoRegistroSalidaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public es.caib.regweb3.ws.api.v3.IdentificadorWs nuevoRegistroSalida(
        @WebParam(name = "entidad", targetNamespace = "")
        java.lang.String entidad,
        @WebParam(name = "registroSalidaWs", targetNamespace = "")
        es.caib.regweb3.ws.api.v3.RegistroSalidaWs registroSalidaWs
    ) throws WsValidationException, WsI18NException;

    @WebMethod
    @RequestWrapper(localName = "obtenerRegistroSalida", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.ObtenerRegistroSalida")
    @ResponseWrapper(localName = "obtenerRegistroSalidaResponse", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.ObtenerRegistroSalidaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public es.caib.regweb3.ws.api.v3.RegistroSalidaResponseWs obtenerRegistroSalida(
        @WebParam(name = "numeroRegistro", targetNamespace = "")
        java.lang.String numeroRegistro,
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "entidad", targetNamespace = "")
        java.lang.String entidad
    ) throws WsValidationException, WsI18NException;

    @WebMethod
    @RequestWrapper(localName = "anularRegistroSalida", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.AnularRegistroSalida")
    @ResponseWrapper(localName = "anularRegistroSalidaResponse", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.AnularRegistroSalidaResponse")
    public void anularRegistroSalida(
        @WebParam(name = "numeroRegistro", targetNamespace = "")
        java.lang.String numeroRegistro,
        @WebParam(name = "entidad", targetNamespace = "")
        java.lang.String entidad,
        @WebParam(name = "anular", targetNamespace = "")
        boolean anular
    ) throws WsValidationException, WsI18NException;

    @WebMethod
    @RequestWrapper(localName = "getVersion", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.GetVersion")
    @ResponseWrapper(localName = "getVersionResponse", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.GetVersionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getVersion();

    @WebMethod
    @RequestWrapper(localName = "getVersionWs", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.GetVersionWs")
    @ResponseWrapper(localName = "getVersionWsResponse", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.GetVersionWsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int getVersionWs();

    @WebMethod
    @RequestWrapper(localName = "altaRegistroSalida", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.AltaRegistroSalida")
    @ResponseWrapper(localName = "altaRegistroSalidaResponse", targetNamespace = "http://impl.v3.ws.regweb3.caib.es/", className = "es.caib.regweb3.ws.api.v3.AltaRegistroSalidaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public es.caib.regweb3.ws.api.v3.IdentificadorWs altaRegistroSalida(
        @WebParam(name = "registroSalidaWs", targetNamespace = "")
        es.caib.regweb3.ws.api.v3.RegistroSalidaWs registroSalidaWs
    ) throws WsValidationException, WsI18NException;
}
