package org.plugin.geiser.api;

public enum EstadoRegistro {

	SIN_DATOS,
	PENDIENTE_ENVIO,
	ENVIADO_PENDIENTE_CONFIRMACION,
	ENVIADO_PENDIENTE_CONFIRMACION_MANUAL,
	RECIBIDO_PENDIENTE_CONFIRMACION,
	RECIBIDO_PENDIENTE_CONFIRMACION_MANUAL,
	ENVIADO_CONFIRMADO,
	RECIBIDO_CONFIRMADO,
	ENVIADO_RECHAZADO,
	RECIBIDO_RECHAZADO,
	ANULADO,
	REENVIADO,
	EN_TRAMITE,
	ASIGNADO,
	FINALIZADO,
	REENVIADO_RECHAZADO,
	RECTIFICADO,
	ENVIO_PROCESO,
	RECIBIDO_RECHAZADO_CIUDADANO
	
}
