package org.plugin.geiser.api;

public enum TipoRespuesta {

	OK,
	ERROR_INTERNAL,
	ERROR_AUTHENTICATION,
	ERROR_AUTHORIZATION,
	ERROR_CONVERSION,
	ERROR_VALIDATOR,
	WARNING_NOTFOUND,
	WARNING_MAXLIMIT,
	WARNING_DUPLICATE,
	WARNING_ANEXO_CONTENT_DELETED
	
}
