
/*
 * 
 */

package es.caib.regweb.ws.api.v3;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.12-patch-04
 * Mon Mar 09 09:29:57 CET 2015
 * Generated source version: 2.2.12-patch-04
 * 
 */


@WebServiceClient(name = "RegWebRegistroEntradaWsService", 
                  wsdlLocation = "http://localhost:8080/regweb/ws/v3/RegWebRegistroEntrada?wsdl",
                  targetNamespace = "http://impl.v3.ws.regweb.caib.es/") 
public class RegWebRegistroEntradaWsService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://impl.v3.ws.regweb.caib.es/", "RegWebRegistroEntradaWsService");
    public final static QName RegWebRegistroEntradaWs = new QName("http://impl.v3.ws.regweb.caib.es/", "RegWebRegistroEntradaWs");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/regweb/ws/v3/RegWebRegistroEntrada?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:8080/regweb/ws/v3/RegWebRegistroEntrada?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public RegWebRegistroEntradaWsService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RegWebRegistroEntradaWsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RegWebRegistroEntradaWsService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns RegWebRegistroEntradaWs
     */
    @WebEndpoint(name = "RegWebRegistroEntradaWs")
    public RegWebRegistroEntradaWs getRegWebRegistroEntradaWs() {
        return super.getPort(RegWebRegistroEntradaWs, RegWebRegistroEntradaWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RegWebRegistroEntradaWs
     */
    @WebEndpoint(name = "RegWebRegistroEntradaWs")
    public RegWebRegistroEntradaWs getRegWebRegistroEntradaWs(WebServiceFeature... features) {
        return super.getPort(RegWebRegistroEntradaWs, RegWebRegistroEntradaWs.class, features);
    }

}
