package es.caib.regweb.ws.api.v3;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.12-patch-04
 * Mon Dec 15 12:12:39 CET 2014
 * Generated source version: 2.2.12-patch-04
 * 
 */
 
@WebService(targetNamespace = "http://personas.impl.v3.ws.regweb.caib.es/", name = "RegWebPersonasWs")
@XmlSeeAlso({ObjectFactory.class})
public interface RegWebPersonasWs {

    @RequestWrapper(localName = "borrarPersona", targetNamespace = "http://personas.impl.v3.ws.regweb.caib.es/", className = "es.caib.regweb.ws.api.v3.BorrarPersona")
    @WebMethod
    @ResponseWrapper(localName = "borrarPersonaResponse", targetNamespace = "http://personas.impl.v3.ws.regweb.caib.es/", className = "es.caib.regweb.ws.api.v3.BorrarPersonaResponse")
    public void borrarPersona(
        @WebParam(name = "personaID", targetNamespace = "")
        java.lang.Long personaID
    ) throws WsI18NException;

    @RequestWrapper(localName = "actualizarPersona", targetNamespace = "http://personas.impl.v3.ws.regweb.caib.es/", className = "es.caib.regweb.ws.api.v3.ActualizarPersona")
    @WebMethod
    @ResponseWrapper(localName = "actualizarPersonaResponse", targetNamespace = "http://personas.impl.v3.ws.regweb.caib.es/", className = "es.caib.regweb.ws.api.v3.ActualizarPersonaResponse")
    public void actualizarPersona(
        @WebParam(name = "personaWs", targetNamespace = "")
        es.caib.regweb.ws.api.v3.PersonaWs personaWs
    ) throws WsI18NException, WsValidationException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getVersion", targetNamespace = "http://personas.impl.v3.ws.regweb.caib.es/", className = "es.caib.regweb.ws.api.v3.GetVersion")
    @WebMethod
    @ResponseWrapper(localName = "getVersionResponse", targetNamespace = "http://personas.impl.v3.ws.regweb.caib.es/", className = "es.caib.regweb.ws.api.v3.GetVersionResponse")
    public java.lang.String getVersion();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "listarPersonas", targetNamespace = "http://personas.impl.v3.ws.regweb.caib.es/", className = "es.caib.regweb.ws.api.v3.ListarPersonas")
    @WebMethod
    @ResponseWrapper(localName = "listarPersonasResponse", targetNamespace = "http://personas.impl.v3.ws.regweb.caib.es/", className = "es.caib.regweb.ws.api.v3.ListarPersonasResponse")
    public java.util.List<es.caib.regweb.ws.api.v3.PersonaWs> listarPersonas(
        @WebParam(name = "entidadCodigoDir3", targetNamespace = "")
        java.lang.String entidadCodigoDir3
    ) throws WsI18NException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "crearPersona", targetNamespace = "http://personas.impl.v3.ws.regweb.caib.es/", className = "es.caib.regweb.ws.api.v3.CrearPersona")
    @WebMethod
    @ResponseWrapper(localName = "crearPersonaResponse", targetNamespace = "http://personas.impl.v3.ws.regweb.caib.es/", className = "es.caib.regweb.ws.api.v3.CrearPersonaResponse")
    public java.lang.Long crearPersona(
        @WebParam(name = "personaWs", targetNamespace = "")
        es.caib.regweb.ws.api.v3.PersonaWs personaWs
    ) throws WsI18NException, WsValidationException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getVersionWs", targetNamespace = "http://personas.impl.v3.ws.regweb.caib.es/", className = "es.caib.regweb.ws.api.v3.GetVersionWs")
    @WebMethod
    @ResponseWrapper(localName = "getVersionWsResponse", targetNamespace = "http://personas.impl.v3.ws.regweb.caib.es/", className = "es.caib.regweb.ws.api.v3.GetVersionWsResponse")
    public int getVersionWs();
}
