package es.caib.regweb.ws.api.v3;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.12-patch-04
 * Mon Dec 15 12:12:45 CET 2014
 * Generated source version: 2.2.12-patch-04
 * 
 */
 
@WebService(targetNamespace = "http://registroentrada.impl.v3.ws.regweb.caib.es/", name = "RegWebRegistroEntradaWs")
@XmlSeeAlso({ObjectFactory.class})
public interface RegWebRegistroEntradaWs {

    @RequestWrapper(localName = "anularRegistroEntrada", targetNamespace = "http://registroentrada.impl.v3.ws.regweb.caib.es/", className = "es.caib.regweb.ws.api.v3.AnularRegistroEntrada")
    @WebMethod
    @ResponseWrapper(localName = "anularRegistroEntradaResponse", targetNamespace = "http://registroentrada.impl.v3.ws.regweb.caib.es/", className = "es.caib.regweb.ws.api.v3.AnularRegistroEntradaResponse")
    public void anularRegistroEntrada(
        @WebParam(name = "numeroRegistroFormateado", targetNamespace = "")
        java.lang.String numeroRegistroFormateado,
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "entidad", targetNamespace = "")
        java.lang.String entidad,
        @WebParam(name = "anular", targetNamespace = "")
        boolean anular
    ) throws WsI18NException, WsValidationException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "obtenerRegistroEntradaID", targetNamespace = "http://registroentrada.impl.v3.ws.regweb.caib.es/", className = "es.caib.regweb.ws.api.v3.ObtenerRegistroEntradaID")
    @WebMethod
    @ResponseWrapper(localName = "obtenerRegistroEntradaIDResponse", targetNamespace = "http://registroentrada.impl.v3.ws.regweb.caib.es/", className = "es.caib.regweb.ws.api.v3.ObtenerRegistroEntradaIDResponse")
    public es.caib.regweb.ws.api.v3.IdentificadorWs obtenerRegistroEntradaID(
        @WebParam(name = "any", targetNamespace = "")
        int any,
        @WebParam(name = "numeroRegistro", targetNamespace = "")
        int numeroRegistro,
        @WebParam(name = "libro", targetNamespace = "")
        java.lang.String libro,
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "entidad", targetNamespace = "")
        java.lang.String entidad
    ) throws WsI18NException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getVersionWs", targetNamespace = "http://registroentrada.impl.v3.ws.regweb.caib.es/", className = "es.caib.regweb.ws.api.v3.GetVersionWs")
    @WebMethod
    @ResponseWrapper(localName = "getVersionWsResponse", targetNamespace = "http://registroentrada.impl.v3.ws.regweb.caib.es/", className = "es.caib.regweb.ws.api.v3.GetVersionWsResponse")
    public int getVersionWs();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getVersion", targetNamespace = "http://registroentrada.impl.v3.ws.regweb.caib.es/", className = "es.caib.regweb.ws.api.v3.GetVersion")
    @WebMethod
    @ResponseWrapper(localName = "getVersionResponse", targetNamespace = "http://registroentrada.impl.v3.ws.regweb.caib.es/", className = "es.caib.regweb.ws.api.v3.GetVersionResponse")
    public java.lang.String getVersion();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "obtenerRegistroEntrada", targetNamespace = "http://registroentrada.impl.v3.ws.regweb.caib.es/", className = "es.caib.regweb.ws.api.v3.ObtenerRegistroEntrada")
    @WebMethod
    @ResponseWrapper(localName = "obtenerRegistroEntradaResponse", targetNamespace = "http://registroentrada.impl.v3.ws.regweb.caib.es/", className = "es.caib.regweb.ws.api.v3.ObtenerRegistroEntradaResponse")
    public es.caib.regweb.ws.api.v3.RegistroEntradaWs obtenerRegistroEntrada(
        @WebParam(name = "numeroRegistroFormateado", targetNamespace = "")
        java.lang.String numeroRegistroFormateado,
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "entidad", targetNamespace = "")
        java.lang.String entidad
    ) throws WsI18NException, WsValidationException;

    @RequestWrapper(localName = "tramitarRegistroEntrada", targetNamespace = "http://registroentrada.impl.v3.ws.regweb.caib.es/", className = "es.caib.regweb.ws.api.v3.TramitarRegistroEntrada")
    @WebMethod
    @ResponseWrapper(localName = "tramitarRegistroEntradaResponse", targetNamespace = "http://registroentrada.impl.v3.ws.regweb.caib.es/", className = "es.caib.regweb.ws.api.v3.TramitarRegistroEntradaResponse")
    public void tramitarRegistroEntrada(
        @WebParam(name = "numeroRegistroFormateado", targetNamespace = "")
        java.lang.String numeroRegistroFormateado,
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "entidad", targetNamespace = "")
        java.lang.String entidad
    ) throws WsI18NException, WsValidationException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "altaRegistroEntrada", targetNamespace = "http://registroentrada.impl.v3.ws.regweb.caib.es/", className = "es.caib.regweb.ws.api.v3.AltaRegistroEntrada")
    @WebMethod
    @ResponseWrapper(localName = "altaRegistroEntradaResponse", targetNamespace = "http://registroentrada.impl.v3.ws.regweb.caib.es/", className = "es.caib.regweb.ws.api.v3.AltaRegistroEntradaResponse")
    public es.caib.regweb.ws.api.v3.IdentificadorWs altaRegistroEntrada(
        @WebParam(name = "registroEntradaWs", targetNamespace = "")
        es.caib.regweb.ws.api.v3.RegistroEntradaWs registroEntradaWs
    ) throws WsI18NException, WsValidationException;
}
