
package es.caib.regweb.ws.api.v3;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.12-patch-04
 * Mon Dec 15 12:12:51 CET 2014
 * Generated source version: 2.2.12-patch-04
 * 
 */

@WebFault(name = "WsValidationErrors", targetNamespace = "http://registrosalida.impl.v3.ws.regweb.caib.es/")
public class WsValidationException extends Exception {
    public static final long serialVersionUID = 20141215121251L;
    
    private es.caib.regweb.ws.api.v3.WsValidationErrors wsValidationErrors;

    public WsValidationException() {
        super();
    }
    
    public WsValidationException(String message) {
        super(message);
    }
    
    public WsValidationException(String message, Throwable cause) {
        super(message, cause);
    }

    public WsValidationException(String message, es.caib.regweb.ws.api.v3.WsValidationErrors wsValidationErrors) {
        super(message);
        this.wsValidationErrors = wsValidationErrors;
    }

    public WsValidationException(String message, es.caib.regweb.ws.api.v3.WsValidationErrors wsValidationErrors, Throwable cause) {
        super(message, cause);
        this.wsValidationErrors = wsValidationErrors;
    }

    public es.caib.regweb.ws.api.v3.WsValidationErrors getFaultInfo() {
        return this.wsValidationErrors;
    }
}
